PORTNAME=	auto-dev
DISTVERSION=	g20210917
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Tools for automating code development and documentation

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	050247da

NO_BUILD=	yes

.include <bsd.port.mk>
