PORTNAME=	auto-dev
DISTVERSION=	0.0.0-20
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Tools for automating code development and documentation

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	94bff0157006431ec7c1a2cac265286ba711716d

NO_BUILD=	yes

.include <bsd.port.mk>
