PORTNAME=	auto-dev
DISTVERSION=	0.0.0-11
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Tools for automating code development and documentation

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	04f84b135624f674ee9e862c186db5d6402197fe

NO_BUILD=	yes

.include <bsd.port.mk>
