# Created by: Jason Bacon <bacon@unixdev.ceas.uwm.edu>
# $FreeBSD$

PORTNAME=	bedops
PORTVERSION=	2.4.20
DISTVERSIONPREFIX=v
CATEGORIES=	biology

MAINTAINER=	bacon@unixdev.ceas.uwm.edu
COMMENT=	High-performance genomic feature operations

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake

USE_GITHUB=	yes

ALL_TARGET=	default

.include <bsd.port.mk>
