# New ports collection makefile for:	fvcom-spherical
# Date created:			31 Mar 2012
# Whom:				Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

MASTERDIR=	${.CURDIR}/../fvcom

PKGNAMESUFFIX=	-spherical

MAKE_ARGS+=	PORT_CPP_FLAGS+=-DSPHERICAL

.include "../fvcom/Makefile"
