# New ports collection makefile for:	detab
# Date created:		2011-01-04
# Whom:			Jason Bacon <jwb@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	detab
PORTVERSION=	0.1
CATEGORIES=	wip textproc
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Replace tabs a th spaces in a text file

USES=		tar:xz

.include <bsd.port.mk>
