PORTNAME=	multitasking
DISTVERSION=	0.0.9
CATEGORIES=	wip python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Non-blocking Python methods using decorators
WWW=		https://pypi.python.org/pypi/multitasking

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
