PORTNAME=	xdt99
DISTVERSION=	3.6.5
CATEGORIES=	wip emulators python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	TMS 99xx Cross-Development Tools
WWW=		https://github.com/endlos99/xdt99

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	autoplist distutils
USE_GITHUB=	yes
GH_ACCOUNT=	endlos99

.include <bsd.port.mk>
