# New ports collection makefile for:	endian
# Date created:		3 Jan 2006
# Whom:			bacon@smithers.neuro.mcw.edu
#
# $FreeBSD: ports/sysutils/endian/Makefile,v 1.3 2009/06/19 20:06:31 linimon Exp $
#

PORTNAME=	endian
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/ \
		http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Report endianness of a system

MAN1=		endian.1

PLIST_FILES=	bin/endian

.include <bsd.port.mk>
