# Created by: J Bacon
# $FreeBSD: sysutils/endian/Makefile 327772 2013-09-20 23:05:58Z bapt $

PORTNAME=	endian
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/ \
		http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Report endianness of a system

MAN1=		endian.1

PLIST_FILES=	bin/endian

NO_STAGE=	yes
.include <bsd.port.mk>
