# Created by: Jason W. Bacon <jwbacon@tds.net>
# $FreeBSD: head/sysutils/endian/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	endian
PORTVERSION=	1.1
CATEGORIES=	sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/ \
		http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Report endianness of a system

USES=		tar:xz

PLIST_FILES=	bin/endian

MAKE_ARGS=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
