# Created by: Jason Bacon <bacon@zebra.acadix.biz>
# $FreeBSD$

PORTNAME=	linux-birdsuite
PORTVERSION=	
CATEGORIES=	biology
MASTER_SITES=	https://www.broadinstitute.org/ftp/pub/mpg/birdsuite/
DISTNAME=	MCRInstaller.75.glnxa64.bin

MAINTAINER=	bacon@zebra.acadix.biz
COMMENT=	

USES=		gz

LICENSE=	
LICENSE_FILE=	

#    Java 1.5 or higher http://www.java.com
#    Python 2.5.2 or higher http://www.python.org
#    numpy Python package, version 1.2 or higher http://numpy.scipy.org
#    R 2.4 or higher http://www.r-project.org
#    mclust R package, version 3 or higher
#    http://lib.stat.cmu.edu/R/CRAN/web/packages/mclust/index.html
#    Affymetrix Power Tools (APT) 1.8.6 or 1.10.2, binaries
#    http://www.affymetrix.com/support/developer/powertools/index.affx
#    Affymetrix library bundle for Genome-Wide Human SNP Array 6.0
#    http://www.affymetrix.com/Auth/support/downloads/library_files/genomewidesnp6_libraryfile.zip


.include <bsd.port.mk>
