# Do not upgrade this port beyond 0.1.x before testing with py-qiime

PORTNAME=	qiime-default-reference
PORTVERSION=	0.1.3
CATEGORIES=	wip biology python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Default reference data files for use with QIIME
WWW=		https://pypi.python.org/pypi/qiime-default-reference

LICENSE=	PD
#LICENSE=	CC BY-SA 3.0
#LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
