# New ports collection makefile for:	remountnfs
# Date created:		2008-05-23
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	remountnfs
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Remount all NFS partitions

PLIST_FILES=	bin/remountnfs

MAN1=		remountnfs.1

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
