# New ports collection makefile for:	remountnfs
# Date created:		2008-05-23
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	remountnfs
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Remount all NFS partitions

PLIST_FILES=	bin/remountnfs

MAN1=		remountnfs.1

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
