# Created by: Jason Bacon <jwb@FreeBSD.org>
# $FreeBSD$

PORTNAME=	klustakwik2
PORTVERSION=	0.2.4
CATEGORIES=	wip python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	High-dimensional cluster analysis with masked EM for Gaussian mixtures

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team

.include <bsd.port.mk>
