# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	mvapich2
PORTVERSION=	2.1
CATEGORIES=	net
MASTER_SITES=	http://mvapich.cse.ohio-state.edu/download/mvapich/mv2/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Ohio State University Network-Based Computing Laboratory MPI

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

GNU_CONFIGURE=	yes

USES=		fortran

.include <bsd.port.mk>
