PORTNAME=	readseq
DISTVERSION=	2.1.30-1
CATEGORIES=	wip biology java
MASTER_SITES=	http://iubio.bio.indiana.edu/soft/molbio/readseq/java/
DISTFILES=	${PORTNAME}.jar

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Read & reformat biosequences, Java command-line version

LICENSE=	PD

USE_JAVA=	yes

.include <bsd.port.mk>
