.\" MDOC man page template
.\" Use MDOC only for system-specific man pages where groff is the
.\" default nroff command.  For portable software meant to run on
.\" all *nix platforms, use the older MAN format.  ( *.man in APE )
.Dd 2011-11-03  
.Dt CLUSTER-PORT_ADD 1
.Os
.\"----------------------------------------------------------------------
.Sh NAME
.Nm cluster-port_add
.Nd install a port on compute nodes
.\"----------------------------------------------------------------------
.Sh SYNOPSIS
.\" Form 1
.Nm
.Ar [-p ports-base]
.Ar category/port-name
.\"----------------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
command installs a port from source on all compute nodes using
.Pp
cd ports-base/category/port-name && make install
.Pp
If no ports-base is specified with -p, then /usr/ports is used.
.Sh ENVIRONMENT
.Nm
is affected by all environment variables that impact port building.
.\"----------------------------------------------------------------------
.Sh EXIT STATUS
.Ex -std
.\"----------------------------------------------------------------------
.Sh SEE ALSO
.Xr ports
.Xr cluster-adduser
.Xr cluster-admin
.Xr cluster-cp
.Xr cluster-update-ssh_config
.Xr cluster-pkg_add
.Xr cluster-rmuser
.Xr cluster-run
.Xr cluster-setup
.Xr cluster-shutdown
.\"----------------------------------------------------------------------
.\"----------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared as part of the cluster-admin port in FreeBSD 8.2.
.\"----------------------------------------------------------------------
.Sh AUTHORS
.An Jason Bacon                             
.\"----------------------------------------------------------------------
.Sh BUGS
Yes.
