.Dd June 5, 2010
.Dt CLUSTER-SETUP 1
.Os
.\"----------------------------------------------------------------------
.Sh NAME
.Nm cluster-setup
.Nd Configure a FreeBSD cluster
.\"----------------------------------------------------------------------
.Sh SYNOPSIS
.\" Form 1
.Nm
head|compute
.\"----------------------------------------------------------------------
.Sh PURPOSE
The
.Nm
script semi-automates the process of setting up a simple FreeBSD cluster.
It can help quick-start users who are new to clusters and parallel
programming.  For more experienced users, it
automates the process of setting up and managing a FreeBSD cluster,
saving time and preventing mistakes.
.Pp
At the end of the process, you should have a simple operational cluster
consisting of a single 
.Dq head
node used for job scheduling, monitoring,
and as a file server, and one or more
.Dq compute
nodes used as computational
resources.
.Pp
This system should be ready to run embarrassingly parallel programs
(a.k.a. grid or high-throughput applications) and also compile and run
OpenMPI code (a.k.a. high-performance, distributed parallel applications),
for which there are several books and many online tutorials available.
.\"----------------------------------------------------------------------
.Sh DESCRIPTION
Using
.Nm
involves the following steps:
.Pp
.\" ~~~~~~~~~~~~~~~~ Begin enumerated list
.Bl -enum -compact
.It
Gather two or more computers capable of running the exact same
version of FreeBSD.
.It
Make sure you have sufficient power for all the machines, and a way
to access the console on every machine, such as a KVM switch.
.It
Designate one of the computers as the head node.  The rest
will be compute nodes.  The head node is
where programs will be dispatched from, and may or may not
be a compute node as well.  The head node is usually used for computation
only on very small clusters.  If your nodes are not all the same, and you
do not what the head node used for computations, 
choose the weakest computer for the head node so that
the compute nodes will have the maximum possible computing power.
.It
Connect all computers to a dedicated high-speed switch.  The head node
may serve as a gateway to the parent network, but a separate router will
make life easier.
.It
Install the exact same version of FreeBSD on all nodes, so that all nodes
can run binaries compiled on any node.  The head node should have local IP
address 192.168.0.2.  Compute nodes should be named compute-001,
compute-002, ... and have IP addresses 192.168.0.11, 192.168.0.12, ...
(the numeric suffix in the name + 10).  Cluster-setup will auto-generate
hosts files with this scheme.  Other hostnames and addresses may be used,
but must be added to /etc/hosts manually.
.It
On the head node, run:
.Pp
.Nm
head
.Pp
.it
On each compute node, run:
.Pp
.Nm
compute
.El
.\" ~~~~~~~~~~~~~~~~ End enumerated list
.Pp
It is strongly recommended that all nodes run exactly the same operating
system (version and architecture).  This is not strictly necessary, but
it greatly simplifies both setup and parallel programming by eliminating
opportunities for incompatibility.  It ensures that all systems can run the
same shared binaries, so you only have to compile your parallel code
once and make it accessible to all nodes.
.Pp
Otherwise, the nodes need not have much in common. The nodes of the cluster
need not have similar hardware configurations and need not be dedicated
to the cluster, i.e. they can all be used as desktop
computers or servers while being part of the cluster.
.Pp
FreeBSD is especially well-suited for such a dual-use configuration, since it
has extremely smooth and intelligent multitasking.  Desktop users are
unlikely to notice that CPU-intensive jobs are running in the background
unless they cause extensive swapping or other heavy disk I/O.  This is true
even on single-core systems.
.\"----------------------------------------------------------------------
.Sh EXIT STATUS
.Ex -std
.\"----------------------------------------------------------------------
.Sh SEE ALSO
.Xr cluster-adduser
.Xr cluster-admin
.Xr cluster-cp
.Xr cluster-update-ssh_config
.Xr cluster-pkg_add
.Xr cluster-port_add
.Xr cluster-rmuser
.Xr cluster-run
.Xr cluster-shutdown
.\"----------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared as a port in Jan 2010.
.\"----------------------------------------------------------------------
.Sh AUTHORS
.An "Jason W. Bacon"
.\"----------------------------------------------------------------------
.Sh BUGS
Yes.
