.\" MDOC man page template
.\" Use MDOC only for system-specific man pages where groff is the
.\" default nroff command.  For portable software meant to run on
.\" all *nix platforms, use the older MAN format.  ( *.man in APE )
.Dd 2011-11-03  
.Dt CLUSTER-ADMIN 1
.Os
.\"----------------------------------------------------------------------
.Sh NAME
.Nm cluster-admin
.Nd cluster administration menu
.\"----------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.\"----------------------------------------------------------------------
.Sh PURPOSE
The
.Nm
command presents a simple text menu for cluster administration commands
included in the cluster-admin port.
.\"----------------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
command presents a menu of cluster administration tasks corresponding
to cluster-admin commands such as cluster-adduser, cluster-run, etc.
.\"
.\"----------------------------------------------------------------------
.Sh EXIT STATUS
.Ex -std
.\"----------------------------------------------------------------------
.Sh SEE ALSO
.Xr cluster-cp
.Xr cluster-update-ssh_config
.Xr cluster-pkg_add
.Xr cluster-port_add
.Xr cluster-rmuser
.Xr cluster-run
.Xr cluster-setup
.Xr cluster-shutdown
.\"----------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared as a port in FreeBSD 8.2.
.\"----------------------------------------------------------------------
.Sh AUTHORS
.An "Jason W. Bacon"
.\"----------------------------------------------------------------------
.Sh BUGS
Yes.
