.\" MDOC man page template
.\" Use MDOC only for system-specific man pages where groff is the
.\" default nroff command.  For portable software meant to run on
.\" all *nix platforms, use the older MAN format.  ( *.man in APE )
.Dd 2011-11-03  
.Dt CLUSTER-ADDUSER 1
.Os
.\"----------------------------------------------------------------------
.Sh NAME
.Nm cluster-adduser
.Nd Add a user to a cluster
.\"----------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.\"----------------------------------------------------------------------
.Sh PURPOSE
The
.Nm
command adds a user account to all nodes on a cluster.
.\"----------------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
command prompts for basic information about a new user and performs
all necessary configuration for the user across the cluster, including
creating accounts on all nodes, initializing the user's dot files for
password-less login, etc.
.Pp
.Nm
is run only on the head node, and only after configuration using
cluster-setup is complete.
.Pp
If an LDAP authentication setup is detected on the head node,
.Nm
will attempt to retrieve user information from the LDAP server.
.\"
.\"----------------------------------------------------------------------
.Sh EXIT STATUS
.Ex -std
.\"----------------------------------------------------------------------
.Sh SEE ALSO
.Xr cluster-admin
.Xr cluster-cp
.Xr cluster-update-ssh_config
.Xr cluster-pkg_add
.Xr cluster-port_add
.Xr cluster-rmuser
.Xr cluster-run
.Xr cluster-setup
.Xr cluster-shutdown
.\"----------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared as a port in FreeBSD 8.2.
.\"----------------------------------------------------------------------
.Sh AUTHORS
.An "Jason W. Bacon"
.\"----------------------------------------------------------------------
.Sh BUGS
Yes.
