.\" MDOC man page template
.\" Use MDOC only for system-specific man pages where groff is the
.\" default nroff command.  For portable software meant to run on
.\" all *nix platforms, use the older MAN format.  ( *.man in APE )
.Dd 2011-11-03  
.Dt CLUSTER-PKG_ADD 1
.Os
.\"----------------------------------------------------------------------
.Sh NAME
.Nm cluster-pkg_add
.Nd install a package on compute nodes
.\"----------------------------------------------------------------------
.Sh SYNOPSIS
.\" Form 1
.Nm
.Ar package-name
.\"----------------------------------------------------------------------
.Sh DESCRIPTION
The
.Nm
command installs a package on all compute nodes using
"pkg_add -r package-name".
.Pp
.Sh ENVIRONMENT
Since
.Nm
runs pkg_add, see the environment section of the pkg_add man page.
.\"----------------------------------------------------------------------
.Sh EXIT STATUS
.Ex -std
.\"----------------------------------------------------------------------
.Sh SEE ALSO
.Xr pkg_add
.Xr cluster-adduser
.Xr cluster-admin
.Xr cluster-cp
.Xr cluster-update-ssh_config
.Xr cluster-port_add
.Xr cluster-rmuser
.Xr cluster-run
.Xr cluster-setup
.Xr cluster-shutdown
.\"----------------------------------------------------------------------
.\"----------------------------------------------------------------------
.Sh HISTORY
The
.Nm
command first appeared as part of the cluster-admin port in FreeBSD 8.2.
.\"----------------------------------------------------------------------
.Sh AUTHORS
.An Jason Bacon                             
.\"----------------------------------------------------------------------
.Sh BUGS
Yes.
