# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	spikedetekt2
PORTVERSION=	0.3.0
CATEGORIES=	python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Detecting and extracting spikes from raw recordings

# LICENSE=

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team
GH_TAGNAME=	v${PORTVERSION}

.include <bsd.port.mk>
