# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: head/math/mumps-mpich/Makefile 354002 2014-05-13 21:45:49Z thierry $

MASTERDIR=		${.CURDIR}/../mumps

WITH_OPENMPI=		yes

.include "../mumps/Makefile"
