PORTNAME=	alberta
PORTVERSION=	2.0.1
CATEGORIES=	wip math
MASTER_SITES=	http://www.alberta-fem.de/Downloads/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Adaptive multiLevel finite element toolbox

LIB_DEPENDS=	blas:math/blas

USE_FORTRAN=	yes
GNU_CONFIGURE=	yes
USE_GL=		yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
