# $FreeBSD$

PORTNAME=	gemtools
DISTVERSIONPREFIX=	v
DISTVERSION=	1.7.1
CATEGORIES=	wip python
#MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	C API and a Python module to support and simplify usage of the GEM Mapper

# Check
LICENSE=	GPLv2

USES=		python
USE_GITHUB=	yes
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
