PORTNAME=	libxtend
DISTVERSION=	0.2.1-32
DISTVERSIONSUFFIX=	-gd4181a3
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Miscellaneous functions to extend libc
WWW=		https://github.com/outpaddling/libxtendc

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
USE_LDCONFIG=	yes

GH_ACCOUNT=	outpaddling

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
