
PORTNAME=	bx
PORTVERSION=	0.3.0
CATEGORIES=	wip devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Simple in-memory storage for Python

LICENSE=	MIT
#LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
