# New ports collection makefile for:	ffmap
# Date created:		4 jan 2007
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	ffmap
PORTVERSION=	1.0
CATEGORIES=	science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Functional Field Map

BUILD_DEPENDS=	${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

PLIST_FILES=	bin/ffmap

MAN1=		ffmap.1

.include <bsd.port.mk>
