
PORTNAME=	external-ip
PORTVERSION=	0.1
CATEGORIES=	wip
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Determine IP address of client as seen by server

LICENSE=	BSD2CLAUSE

USES=		tar:xz

USE_RC_SUBR=	reflectipd

PLIST_FILES=	bin/externalip bin/reflectipd

.include <bsd.port.mk>
