# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	external-ip
PORTVERSION=	0.1
CATEGORIES=	wip
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Determine IP address of client as seen by server

LICENSE=	BSD2CLAUSE

USES=		tar:xz

PLIST_FILES=	bin/external-ip bin/reflect-ipd

.include <bsd.port.mk>
