PORTNAME=	libpare
DISTVERSION=	1.1.1-12
DISTVERSIONSUFFIX=	-gab3da2e
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Pointer Array Regular Expressions
WWW=		https://github.com/outpaddling/libpare

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

MAKE_ENV=	MANPREFIX=${PREFIX}/share

PLIST_FILES=	lib/libpare.a \
		include/pare.h \
		share/man/man3/pare.3.gz

.include <bsd.port.mk>
