PORTNAME=		murmurhash
DISTVERSIONPREFIX=	v
DISTVERSION=		1.0.1
CATEGORIES=		wip devel python
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Cython bindings for MurmurHash2

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
USE_GITHUB=	yes

GH_ACCOUNT=	explosion

.include <bsd.port.mk>
