
PORTNAME=	mvapich2
PORTVERSION=	2.1
CATEGORIES=	wip net
MASTER_SITES=	http://mvapich.cse.ohio-state.edu/download/mvapich/mv2/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Ohio State University Network-Based Computing Laboratory MPI

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

GNU_CONFIGURE=	yes

USES=		fortran

.include <bsd.port.mk>
