PORTNAME=	ftpretty
DISTVERSION=	0.4.0
CATEGORIES=	wip ftp python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Wrapper for simple FTP operations: get, put, list etc
WWW=		https://pypi.python.org/project/ftpretty/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	autoplist pep517

.include <bsd.port.mk>
