# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	vcftools
# Specific version demanded by dDocent
PORTVERSION=	0.1.11
CATEGORIES=	biology
MASTER_SITES=	SF/vcftools
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=

USES=		gmake

.include <bsd.port.mk>
