PORTNAME=	npmount
DISTVERSION=	0.1.0-6
DISTVERSIONSUFFIX=	-g9fd101d
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Command line tool for non-privileged [un]mount
WWW=		https://github.com/outpaddling/npmount

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libxtend.so:wip/libxtend

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

.include <bsd.port.mk>
