# Created by: Jason Bacon <jwb@FreeBSD.org>
# $FreeBSD$

PORTNAME=	snpfinder
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0.0
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Simple alignment-based haplotype variant caller

LICENSE=	NONE

USES=		gmake compiler:c++11-lang
USE_GITHUB=	yes
GH_ACCOUNT=	cdeanj

PLIST_FILES=	bin/snpfinder

.include <bsd.port.mk>
