# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	merlin
PORTVERSION=	1.1.2
CATEGORIES=	biology
MASTER_SITES=	http://csg.sph.umich.edu/abecasis/Merlin/download/

USES=		gmake

MAINTAINER=	jwbacon@tds.net
COMMENT=	Sparse trees to represent gene flow in pedigrees

# Depends on pedstats

.include <bsd.port.mk>
