#!/bin/sh -e

printf "Cleaning...\n"
cd /usr/ports/wip
for dir in *; do
    if [ -d $dir/work ] || [ -e $dir/work-py* ]; then
	cd $dir
	pwd
	make clean
	cd ..
    fi
done

find . -name '.*.bak' -exec rm '{}' \;
