#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

for dir in */*; do
    if [ -e /usr/ports/$dir ]; then
	diff -ruN /usr/ports/$dir $dir | more
	pause
    fi
done

