#!/bin/sh -e

##########################################################################
#   Script description:
#       Check out a copy of FreeBSD ports wip and modify the ports
#       configuration to accomodate the wip category.
#
#   History:
#   Date        Name        Modification
#   2017-02-11  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# = 1 ]; then
    if [ $1 = svn ]; then
	printf "Subversion is no longer supported.  Using git...\n"
	pause
    fi
elif [ $# != 0 ]; then
    usage
fi

if [ -z $PORTSDIR ]; then
    PORTSDIR=/usr/ports
fi

if which git > /dev/null 2>&1; then
    git=`which git`
else
    git=/usr/local/bin/git
fi
if [ ! -e $git ]; then
    pkg install -y git
fi
$git clone \
    https://github.com/outpaddling/freebsd-ports-wip \
    $PORTSDIR/wip
cd $PORTSDIR/wip

printf "\nEditing .gitconfig.\n\n"

printf "Full name? "
read name

printf "Email? "
read email

printf "Editor? [vi] "
read editor
if [ 0$editor = 0 ]; then
    editor=vi
fi
git config user.name "$name"
git config user.email "$email"
git config core.editor "$editor"
git config pull.rebase false

if ! fgrep 'USE_LOCAL_MK=yes' /etc/make.conf > /dev/null; then
    cat << EOM >> /etc/make.conf

# Added by freebsd-wip-checkout
USE_LOCAL_MK=yes
# End addition

EOM
fi

if ! fgrep 'VALID_CATEGORIES+=wip' $PORTSDIR/Mk/bsd.local.mk > /dev/null; then
    cat << EOM >> $PORTSDIR/Mk/bsd.local.mk

# Added by freebsd-wip-checkout
VALID_CATEGORIES+=wip
# End addition

EOM
fi

cd $PORTSDIR/wip/wip-tools && make deinstall clean install
cat << EOM

Run wip-update frequently to keep up with the latest WIP ports.

See $PORTSDIR/wip/README for basic info.

EOM
