#!/bin/sh -e

##########################################################################
#   Script description:
#       Check out a copy of FreeBSD ports wip and modify the ports
#       configuration to accomodate the wip category.
#
#   Arguments:
#       svn|git
#
#   History:
#   Date        Name        Modification
#   2017-02-11  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 git|svn\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

if [ -z $PORTSDIR ]; then
    PORTSDIR=/usr/ports
fi

rcs=$1

if [ $rcs = svn ]; then
    if which svn; then
	svn=`which svn`
    else
	svn=/usr/bin/svnlite
    fi
    $svn co \
	https://github.com/outpaddling/freebsd-ports-wip/trunk \
	$PORTSDIR/wip
elif [ $rcs = git ]; then
    if which git; then
	git=`which git`
    else
	git=/usr/local/bin/git
    fi
    if [ ! -e $git ]; then
	pkg install -y git
    fi
    $git clone \
	https://github.com/outpaddling/freebsd-ports-wip \
	$PORTSDIR/wip
else
    printf "Invalid RCS: $rcs\n"
    exit 1
fi

if ! fgrep 'USE_LOCAL_MK=yes' /etc/make.conf > /dev/null; then
    cat << EOM >> /etc/make.conf

# Added by freebsd-wip-checkout
USE_LOCAL_MK=yes
# End addition

EOM
fi

if ! fgrep 'VALID_CATEGORIES+=wip' $PORTSDIR/Mk/bsd.local.mk > /dev/null; then
    cat << EOM >> $PORTSDIR/Mk/bsd.local.mk

# Added by freebsd-wip-checkout
VALID_CATEGORIES+=wip
# End addition

EOM
fi

cd $PORTSDIR/wip/wip-tools && make deinstall clean install
cat << EOM

Run wip-update frequently to keep up with the latest WIP ports.

See $PORTSDIR/wip/README for basic info.

EOM
