PORTNAME=       parasail
DISTVERSIONPREFIX=	v
DISTVERSION=    2.4.3
CATEGORIES=     wip biology

MAINTAINER=     jwb@FreeBSD.org
COMMENT=        SIMD C library for DNA alignments

# Batelle BSD
LICENSE=        BSD2CLAUSE
LICENSE_FILE=   ${WRKSRC}/LICENSE.md

USES=		autoreconf
USE_GITHUB=	yes

GNU_CONFIGURE=	yes

GH_ACCOUNT=	jeffdaily

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
