
# Only 2.0 is compatible with qiime 1.9.1
# https://github.com/biocore/sortmerna#third-party-libraries
PORTNAME=	sortmerna
#PORTVERSION=	2.1
PORTVERSION=	2.0
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Filtering, mapping and OTU-picking NGS reads

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE.LESSER.txt

USE_GITHUB=	yes
GH_ACCOUNT=	biocore

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
