# $FreeBSD$

PORTNAME=	ape
DISTVERSION=	4.1
CATEGORIES=	wip biology
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	bacon@imacbsd.acadix.biz
COMMENT=	Functions for phylogenetic trees

LICENSE=	GPLv2
#LICENSE_FILE=	

# Imports: nlme, lattice, graphics, methods, stats, tools, utils, parallel

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
