# New ports collection makefile for:	openlb
# Date created:		2012-02-25
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	openlb
PORTVERSION=	0.7r0
CATEGORIES=	science math
MASTER_SITES=	http://www.optilb.com/openlb/wp-content/uploads/2012/02/
DISTNAME=	olb-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Open Source lattice Boltzmann code

USE_GMAKE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
