# $FreeBSD$

PORTNAME=	fenics
PORTVERSION=	2017.2.0
CATEGORIES=	wip math python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Computing platform for solving partial differential equations

LICENSE=	LGPL3

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}dijitso>0:wip/py-dijitso \
		${PYTHON_PKGNAMEPREFIX}ffc>0:wip/py-ffc \
		${PYTHON_PKGNAMEPREFIX}fiat>0:wip/py-fiat \
		${PYTHON_PKGNAMEPREFIX}instant>0:wip/py-instant \
		${PYTHON_PKGNAMEPREFIX}ufl>0:wip/py-ufl

USES=		metaport python

.include <bsd.port.mk>
