--- pyproject.toml.orig	2025-06-09 12:58:52 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=65.0.0", "wheel", "setuptools-git-versioning"]
+requires = ["setuptools>=63.0.0", "wheel", "setuptools-git-versioning"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools.packages]
