# Created by: Artyom Mirgorodskiy <artyom.mirgorodsky@gmail.com>

PORTNAME=	mksh
PORTVERSION=	39
CATEGORIES=	wip shells

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Korn shell

DESCR=		${.CURDIR}/../../shells/${PORTNAME}/pkg-descr
RPMVERSION=	10.el6
USES=		linux:c6
USE_LDCONFIG=	yes
# USE_LINUX=	libssh2 nspr nss openldap
USE_LINUX_RPM=	nolib

.include <bsd.port.mk>
