
PORTNAME=	1Dmean
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Calculate statistics on 1D files

PLIST_FILES=	bin/1Dmean \
		bin/1Dstdev \
		bin/1Dnormmcw

MAN1=		1Dmean.1 \
		1Dstdev.1 \
		1Dnormmcw.1

.include <bsd.port.mk>
