PORTNAME=	auto-admin
DISTVERSION=	0.8.0-43
DISTVERSIONSUFFIX=	-gf3502dd
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Portable tools for automating systems management
WWW=		https://github.com/outpaddling/auto-admin

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

MAKE_ENV=	MANDIR=${PREFIX}/share/man

NO_BUILD=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
