PORTNAME=	auto-admin
DISTVERSION=	0.7.16-9
DISTVERSIONSUFFIX=	-g78125f1
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Portable tools for automating systems management
WWW=		https://acadix.biz/auto-admin.php

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

NO_BUILD=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
