# $FreeBSD$

PORTNAME=		DAZZ_DB
# Must use the same version of dazz_db, daligner, pypeflow, and falcon!
DISTVERSIONPREFIX=	V
DISTVERSION=		1.0-14
DISTVERSIONSUFFIX=	-g7104852
CATEGORIES=		wip biology databases

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Dresden assembler for long read DNA projects

LICENSE=	BSD3CLAUSE

USES=		gmake tar:xz
USE_GITHUB=	yes
GH_ACCOUNT=	PacificBiosciences

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
