PORTNAME=	detonate
PORTVERSION=	1.8.1
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	DE novo TranscriptOme rNa-seq Assembly with or without the Truth Evaluation
WWW=		https://deweylab.biostat.wisc.edu/detonate/

# FIXME: Not sure
LICENSE=	PD
#LICENSE_FILE=	

USE_GITHUB=	yes
GH_ACCOUNT=	deweylab

.include <bsd.port.mk>
