# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	cpat
PORTVERSION=	1.2
CATEGORIES=	biology
MASTER_SITES=	SF

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Overcomes alignment search limitations using logistic regression model

LICENSE=	GPLv2
#LICENSE_FILE=

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/cpat man/man6/cpat.6.gz

.include <bsd.port.mk>
