# $FreeBSD$

PORTNAME=	Prodigal
DISTVERSIONPREFIX=	v
DISTVERSION=	2.6.3
CATEGORIES=	wip

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Gene prediction software

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	hyattpd

.include <bsd.port.mk>
