PORTNAME=	gdist
DISTVERSION=	1.0.3
CATEGORIES=	wip math python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Compute geodesic distances
WWW=		https://pypi.python.org/project/gdist/

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
