# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	multichoose
PORTVERSION=	a35c94abd1b312fdcc10455f90b6e527c271bb35
CATEGORIES=	math

MAINTAINER=	jwbacon@tds.net
COMMENT=	Generate multiset combinations (n multichoose k)

LICENSE=	MIT

USES=		shebangfix
SHEBANG_FILES=	*.py

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
