# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	wgs
PORTVERSION=	8.3rc2
CATEGORIES=
MASTER_SITES=	SF/wgs-assembler/wgs-assembler/${PORTNAME}-8.3/
# http://downloads.sourceforge.net/project/wgs-assembler/wgs-assembler/wgs-8.3/wgs-8.3rc2.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fwgs-assembler%2Ffiles%2Fwgs-assembler%2Fwgs-8.3%2F&ts=1439218560&use_mirror=iweb

MAINTAINER=	jwbacon@tds.net
COMMENT=

USES=		tar:bz2

.include <bsd.port.mk>
