
PORTNAME=	inchworm
PORTVERSION=	03132011
CATEGORIES=	wip biology
# MASTER_SITES=	http://downloads.sourceforge.net/project/inchworm/
MASTER_SITES=	SF/inchworm
EXTRACT_SUFX=	.tgz

MAINTAINER=	jwb@FreeBSD.org
COMMENT=

GNU_CONFIGURE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
