# New ports collection makefile for:	visit
# Date created:		2010-12-29
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	visit
PORTVERSION=	2.1.2
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	wip graphics science math
MASTER_SITES=	https://wci.llnl.gov/codes/${PORTNAME}/${PORTVERSION}/
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
DISTNAME=	${PORTNAME}${PORTVERSION}
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bacon4000@gmail.com
COMMENT=	interactive parallel visualization and graphical analysis tool

WRKSRC=		${WRKDIR}/${DISTNAME}/src

HAS_CONFIGURE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
