# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	rsem
PORTVERSION=	1.2.19
CATEGORIES=	biology
MASTER_SITES=	http://deweylab.biostat.wisc.edu/rsem/src/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	RNA-Seq by Expectation-Maximization

LICENSE=	GPLv3

BUILD_DEPENDS+=	samtools01==0.1.19:/usr/wip/biology/samtools0119

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
