# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	canu
PORTVERSION=	1.3
DISTVERSIONPREFIX=v
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	A single molecule sequence assembler for genomes large and small

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/../README.license.GPL

USES=		compiler:openmp gmake

USE_GITHUB=	yes
GH_ACCOUNT=	marbl

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}/src

.include <bsd.port.mk>
