PORTNAME=	auto-sklearn
# DISTVERSIONPREFIX=	v.
DISTVERSION=	0.3.0
CATEGORIES=	wip python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Automated machine learning
WWW=		https://pypi.python.org/pypi/auto-sklearn

LICENSE=	BSD3CLAUSE
# No license file on pypi, maybe use Github?
# LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
# USE_GITHUB=	yes
# GH_ACCOUNT=	automl

.include <bsd.port.mk>
