# $FreeBSD$

PORTNAME=	multiqc
PORTVERSION=	1.7
CATEGORIES=	wip python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	Aggregate results from bioinformatics analyses across many samples

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
