# $FreeBSD$

PORTNAME=	lzstring
PORTVERSION=	1.0.4
CATEGORIES=	wip textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	lz-string for python

LICENSE=	MIT
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
