# $FreeBSD$

PORTNAME=	lzstring
DISTVERSION=	1.0.4
CATEGORIES=	wip archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	LZ-based in-memory string compression

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		python
USE_PYTHON=	autoplist distutils

NO_BUILD=	yes

.include <bsd.port.mk>
