# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	burrito-fillings
PORTVERSION=	0.1.1
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Burrito application controllers for bioinformatics

# Not sure of clauses
LICENSE=	BSD2CLAUSE
# LICENSE_FILE=	

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
