
PORTNAME=	permute
DISTVERSION=	0.9-4
CATEGORIES=	wip math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Restricted permutation designs for freely exchangeable, line transects

LICENSE=	GPLv2
#LICENSE_FILE=

USES=		cran:auto-plist

.include <bsd.port.mk>
