
strblank.o: strblank.c
	${CC} -c ${CFLAGS} strblank.c

tag-list.o: tag-list.c tag-list.h protos.h
	${CC} -c ${CFLAGS} tag-list.c

xml-format.o: xml-format.c tag-list.h xml-format.h protos.h
	${CC} -c ${CFLAGS} xml-format.c

