# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD: head/science/fvcom-mpi/Makefile 397096 2015-09-17 02:58:01Z danilo $

MAINTAINER=	bacon4000@gmail.com

MASTERDIR=	${.CURDIR}/../scotch

WITH_OPENMPI=	yes

.include "${MASTERDIR}/Makefile"
