# $FreeBSD: head/biology/py-dnaio/Makefile 496770 2019-03-24 19:40:26Z jwb $

PORTNAME=	dnaio
DISTVERSION=	0.4
CATEGORIES=	wip biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Read and write FASTQ and FASTA

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.4+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
