# $FreeBSD$

PORTNAME=	q2-feature-classifier
PORTVERSION=	2017.2.0
CATEGORIES=	wip biology python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	QIIME 2 plugin supporting taxonomic classification

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist

USE_GITHUB=	yes
GH_ACCOUNT=	qiime2

.include <bsd.port.mk>
