# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	time
PORTVERSION=	1.7
CATEGORIES=	sysutils
MASTER_SITES=	http://ftp.gnu.org/gnu/time/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	GNU time command

USES=		gmake
GNU_CONFIGURE=	yes

BROKEN=		Does not use destdir

.include <bsd.port.mk>
