# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

# Direct link:		http://downloads.sourceforge.net/project/parafly/parafly-r2013-01-21.tgz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fparafly%2F&ts=1405463589&use_mirror=iweb
# Default attempts:	http://switch.dl.sourceforge.net/project/parafly/parafly/2013.01.21/parafly-2013-01-21.tgz

PORTNAME=	parafly
PORTVERSION=	2013.01.21
CATEGORIES=	sysutils
MASTER_SITES=	SF/${PORTNAME}/
DISTNAME=	${PORTNAME}-r2013-01-21
EXTRACT_SUFX=	.tgz

MAINTAINER=	bacon@unixdev.ceas.uwm.edu
COMMENT=	Process the commands in parallel on a single server

LICENSE=	BSD3CLAUSE

GNU_CONFIGURE=	yes
# OpenMP
USE_GCC=	any

PLIST_FILES=	bin/ParaFly

.include <bsd.port.mk>
