# New ports collection makefile for:	fixperms
# Date created:		4 jan 2007
# Whom:			Jason W. Bacon
#
# $FreeBSD$
#

PORTNAME=	fixperms
PORTVERSION=	0.9
CATEGORIES=	wip sysutils
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Calculate statistics on 1D files

BUILD_DEPENDS=	${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

PLIST_FILES=	bin/fixperms \
		share/examples/fixperms.allow

MAN1=		fixperms.1

.include <bsd.port.mk>
