# Created by: Jason Bacon <bacon@unixdev.ceas.uwm.edu>
# $FreeBSD$

PORTNAME=	fastool
PORTVERSION=
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=
MASTER_SITES=
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
#DISTNAME=
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bacon@unixdev.ceas.uwm.edu
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
