PORTNAME=	metal
DISTVERSION=	2011.03.25
CATEGORIES=	wip biology
MASTER_SITES=	http://csg.sph.umich.edu/abecasis/Metal/download/
DISTNAME=	generic-metal-2011-03-25

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Meta-analysis of genomewide association scans
WWW=		https://genome.sph.umich.edu/wiki/METAL_Program

# For twister, and double check
LICENSE=	BSD3CLAUSE
#LICENSE_FILE=	LICENSE.twister

USES=		gmake

WRKSRC=		${WRKDIR}/generic-metal

INSTALL_TARGET=	install-strip

PLIST_FILES=	bin/metal

.include <bsd.port.mk>
