# $FreeBSD$

PORTNAME=	ffc
# Caution: Must use same version as other FEniCS project ports
DISTVERSION=	2017.1.0
CATEGORIES=	wip python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	FFC-${PORTVERSION}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Compiler for finite element variational forms

LICENSE=	LGPL3+
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
