# $FreeBSD$

PORTNAME=	FFC
DISTVERSION=	2017.1.0
CATEGORIES=	wip python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon@imacbsd.acadix.biz
COMMENT=	Compiler for finite element variational forms

LICENSE=	LGPL3+
# LICENSE_FILE=	

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
