# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	gast
PORTVERSION=	2016.02.10
CATEGORIES=	biology
MASTER_SITES=	https://vamps.mbl.edu/data_downloads/
DISTNAME=	gast_files

MAINTAINER=	bacon4000@gmail.com
COMMENT=

USES=		tar:tgz

.include <bsd.port.mk>
