# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	filevercmp
PORTVERSION=	efdf453ab605880661ede9519bc20f3b8b868b61
CATEGORIES=	sysutils

MAINTAINER=	jwbacon@tds.net
COMMENT=	filevercmp function as in sort --version-sort

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

PLIST_FILES=	bin/filevercmp lib/libfilevercmp.a

.include <bsd.port.mk>
