# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	filevercmp
PORTVERSION=	261142f1529f6b7464f6ad96d0c77872ff919849
CATEGORIES=	sysutils

MAINTAINER=	jwbacon@tds.net
COMMENT=	Filevercmp function as in sort --version-sort

LICENSE=	GPLv3

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

PLIST_FILES=	bin/filevercmp include/filevercmp.h lib/libfilevercmp.a

.include <bsd.port.mk>
