# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	idr
DISTVERSION=	1.2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	jwbacon@tds.net
COMMENT=	Estimating the copula mixture model and plotting correspondence curves

LICENSE=	GPLv3

USES=		cran

.include <bsd.port.mk>
