PORTNAME=	endian
DISTVERSION=	1.1-2
DISTVERSIONSUFFIX=	-g1e679d5
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Report endianness of a system

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/endian man/man1/endian.1.gz

MAKE_ARGS=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
