# Created by: Jason W. Bacon <bacon4000@gmail.com>
# $FreeBSD: head/sysutils/endian/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	endian
PORTVERSION=	1.1
CATEGORIES=	wip sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Report endianness of a system

LICENSE=	BSD2CLAUSE

USES=		tar:xz

PLIST_FILES=	bin/endian man/man1/endian.1.gz

MAKE_ARGS=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
