# $FreeBSD: head/sysutils/endian/Makefile 460452 2018-01-31 01:07:07Z jwb $

PORTNAME=	endian
PORTVERSION=	1.1
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Report endianness of a system

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/endian man/man1/endian.1.gz

MAKE_ARGS=	STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
