# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	rna-pipeline1
PORTVERSION=	0.1
CATEGORIES=	biology
MASTER_SITES=
DISTFILES=

MAINTAINER=	bacon4000@gmail.com
COMMENT=	RNA sequencing pipeline metaport for

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	scythe>=0:/usr/wip/biology/scythe \
		sickle>=0:/usr/wip/biology/sickle \
		bowtie2>=0:/usr/wip/biology/bowtie2 \
		tophat==2.0.12:/usr/wip/biology/tophat2012 \
		cufflinks>=0:/usr/wip/biology/cufflinks

NO_BUILD=	yes

.include <bsd.port.mk>
