PORTNAME=	fastphase
PORTVERSION=	2015.09.17
CATEGORIES=	wip biology
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Haploview is designed to simplify and expedite the process of haplotype analysis by providing a common interface to several tasks relating to such analyses.

#LICENSE=	

USES=		tar:xz

.include <bsd.port.mk>
