# New ports collection makefile for:	dvdformat
# Date created:		8 Nov 2007
# Whom:			Jason W. Bacon
#
# $FreeBSD$
#

PORTNAME=	dvdformat
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/ \
		http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Format a DVDRAM and set ownership

PLIST_FILES=	bin/dvdformat

MAN1=		fixperms.1

.include <bsd.port.mk>
