# $FreeBSD$

PORTNAME=	kwiklib
PORTVERSION=	0.3.0
DISTVERSIONPREFIX=      v
CATEGORIES=	wip math python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Shared features between the projects (files, statistics, utils)

LICENSE=	BSD3CLAUSE

USES=		python:3.6+
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team

.include <bsd.port.mk>
