# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$
#
# Do not upgrade this port beyond 0.2.x before testing with biology/py-qiime

PORTNAME=	scikit-bio
PORTVERSION=	0.2.3
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Data structures, algorithms and educational resources for bioinformatics

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}numpy>0:math/py-numpy

# Not sure about clauses
LICENSE=	BSD2CLAUSE
# LICENSE_FILE=	

USES=		fortran python:2
USE_PYTHON=	distutils

.include <bsd.port.mk>
