# New ports collection makefile for:	libpare
# Date created:		Nov 2006
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	libpare
PORTVERSION=	1.1.1
CATEGORIES=	devel
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/ \
		http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Misc functions

PLIST_FILES=	lib/libpare.a \
		include/pare.h

STRIP_CMD=

CFLAGS=		-g -Wall

MAN3=	pare.3

.include <bsd.port.mk>
