# $FreeBSD: head/biology/fastahack/Makefile 467485 2018-04-16 14:50:46Z jwb $

PORTNAME=		fastahack
DISTVERSIONPREFIX=	v
DISTVERSION=		1.0.0
CATEGORIES=		wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Utility for indexing and sequence extraction from FASTA files

LICENSE=	GPLv2

USE_GITHUB=	yes
GH_ACCOUNT=	ekg

MAKEFILE=	${FILESDIR}/Makefile
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
