# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	fastahack
PORTVERSION=	2015.11.21
CATEGORIES=	wip biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Utilities for indexing and sequence extraction from FASTA files

LICENSE=	GPLv2

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	20cba9157fa0d8e8938f76ff3c9f8437adddd58a

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
