#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 package-name\n"
    exit 1
fi

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

pkg=$1
cluster-run "cluster-local-pkg_add $pkg"

auto-append-line $pkg $pkg /usr/local/cluster/packages.txt nocomment

