#!/bin/sh

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

/usr/local/etc/rc.d/gmetad restart
/usr/local/etc/rc.d/gmond restart

# gmond doesn't restart unless -n is used here.  Why?
cluster-run -n '/usr/local/etc/rc.d/gmond restart'

