#!/bin/sh -e

printf "Hostname? "
read hostname
printf "Cores? "
read cores

# Add node to config files
auto-append-line $hostname $hostname /usr/local/cluster/compute_nodes nocomment
auto-append-line $hostname "$hostname $cores" /usr/local/cluster/compute_nodes nocomment

# Double check config files
vi /usr/local/cluster/compute_nodes
vi /var/spool/torque/server_priv/nodes

# Make sure services are in order on compute node
ssh -t $hostname vi /etc/rc.conf

# Start daemons on compute node
ssh $hostname /usr/local/etc/rc.d/pbs_mom restart
ssh $hostname /usr/local/etc/rc.d/gmond restart

# Signal the PBS server to find the new node without restarting
qmgr -c "create node $hostname np=$cores"
pbsnodes

