#!/bin/sh -e

usage()
{
    printf "Usage: $0 groupname [options]\n"
    printf 'All arguments are passed to "pw groupadd"\n'
    exit 1
}

if [ `whoami` != root ]; then
    printf "$0 must be run as root.\n"
    exit 1
fi

if [ $# -lt 1 ] || [ `echo $1 | cut -c 1,1` = '-' ]; then
    usage
fi

group_name=$1
groupadd_cmd="pw groupadd $*"

# Eval here to expand before running
eval $groupadd_cmd

# FIXME: Factor this assignment out to a separate script
db='/usr/local/cluster/groups.txt'
group_entry=`awk -F : '$1 == "'$group_name'" { print $0 }' /etc/group`
auto-append-line $group_name "$group_entry" $db nocomment

# Do not assume home directories are shared!
for node in `cluster-compute-nodes`; do
    printf "Syncing group $group_name on $node...\n"
    # Do not eval here: ssh starts a remote shell which performs expansion
    ssh $node "cluster-local-sync-group $group_name"
done

