#!/bin/sh -e

usage()
{
    cat << EOM
Usage: $1 [-p] [-c] [-n] 'command'
    -c = continue running if there are errors.
    -p = run in parallel, redirecting output to files. (implies -c)
    -n = omit ssh -t flag to disable full terminal control.
	 Use only if a command has output problems without -n.

    Note: command must be enclosed in quotes.
EOM
    exit 1
}

parallel=0
flags=''
terminal_control=on
while [ 0`printf '%s' $1 | cut -c 1,1` = 0'-' ]; do
    if [ $1 = '-p' ]; then
	parallel=1
	set +e
	shift
    elif [ $1 = '-c' ]; then
	set +e
	shift
    elif [ $1 = '-n' ]; then
	terminal_control=off
	shift
    else
	usage $0
    fi
done

if [ $terminal_control = 'on' ]; then
    flags="${flags} -t"
fi

if [ $# != 1 ]; then
    usage $0
fi

for node in `cluster-compute-nodes`; do
    printf "\n============================================================\n"
    printf "$node\n"
    printf "============================================================\n\n"
    
    if [ $node = "localhost" ]; then
	cmd="sh -c"
    else
	# -t causes ganglia restart to fail
	cmd="ssh $flags $node"
    fi
    
    if [ $parallel = 1 ]; then
	$cmd "$1" > cluster-run.out.$node 2>&1 &
	printf "Output in cluster-run.out.$node.\n"
    else
	$cmd "$1"
    fi
done

if [ $parallel = 1 ]; then
    # Wait for all jobs to complete
    wait
fi

