#!/bin/sh -e

# Run only from head node
if [ `hostname -s` != `cluster-head-node` ]; then
    printf "$0 can only be run on the head node.\n"
    exit 1
fi

cat << EOM

This will kill all running jobs.  Are you sure you want to proceed? (yes/[no])
EOM
read resp
if [ 0$resp != 0yes ]; then
    printf 'Shutdown aborted.\n'
    exit 0
fi

printf "Minutes to shutdown? "
read minutes
if [ 0$minutes != 0 ]; then
    for node in `cluster-compute-nodes`; do
	printf "Shutting down $node...\n"
	ssh $node "shutdown -p +$minutes"
    done
    
    printf "Shut down head? (yes/[no]) "
    read resp
    if [ 0$resp = 0'yes' ]; then
	shutdown -p +$minutes
    fi
fi

