#!/bin/sh -e

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


usage()
{
    printf "Usage: $0 groupname\n"
    exit 1
}


if [ $# != 1 ]; then
    usage
fi

# head or compute node?
cluster_dir='/head_usr/local/cluster'

groupname=$1

gid=`awk -F ':' -v groupname=$groupname '$1 == groupname { print $3 }' $cluster_dir/groups.txt`

if [ 0$gid = 0 ]; then
    printf "group $groupname is not listed in $cluster_dir/groups.txt.\n"
    exit 2
fi

members=`awk -F ':' -v groupname=$groupname \
    '$1 == groupname { print $4 }' $cluster_dir/groups.txt`

if [ ! -e /etc/group.bak ]; then
    cp /etc/group /etc/group.bak
fi

current_gid=`awk -F ':' -v groupname=$groupname '$1 == groupname { print $3 }' /etc/group`
if [ 0$current_gid = 0 ]; then
    printf "Group $groupname does not exist.  Adding...\n"
    cmd="pw groupadd $groupname -g $gid"
    if [ 0$members != 0 ]; then
	cmd="$cmd -M $members"
    fi
    $cmd
elif [ $gid != $current_gid ]; then
    printf "Current group ID ($current_gid) does not match cluster group ID ($gid).  Fixing...\n"
    
    # Fix group entry
    cmd="pw groupmod $groupname -g $gid"
    if [ 0$members != 0 ]; then
	cmd="$cmd -M $members"
    fi
    $cmd
fi

