#!/bin/sh

cat << EOM

This will distribute current files to all compute nodes.  Are you
sure you want to proceed? (y/n)
EOM

read resp
if [ 0$resp != 0y ]; then
    exit 0
fi

repo=/usr/local/cluster/sync-files

cd $repo
for node in `cluster-compute-nodes`; do
    rsync -avR * ${node}:/
done

# Assume login.conf was modified.  No harm in this.
printf "Rebuilding login.conf db...\n"
cluster-run 'cap_mkdb /etc/login.conf'

