#!/bin/sh

if [ $# -lt 2 ]; then
    printf "Usage: $0 src [src ...] dest-dir\n"
    exit 1
fi

src=''
while [ $# -gt 1 ]; do
    src="$src $1"
    shift
done
echo $src
dest=$1
echo $dest

# Localhost
printf "localhost\n"
cp $src $dest

# Nodes
for node in `cat /usr/local/cluster/compute_nodes`; do
    printf "$node\n"
    scp $src $node:$dest
done

