PORTNAME=	q2-deblur
DISTVERSION=	2020.11.1
CATEGORIES=	wip biology python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	QIIME 2 Deblur plugin for quality control

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	distutils autoplist
USE_GITHUB=	yes

GH_ACCOUNT=	qiime2

.include <bsd.port.mk>
