#
# $FreeBSD$
#

PORTNAME=	sage
PORTVERSION=	5.5
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	wip math
MASTER_SITES=	http://mirrors.xmission.com/sage/src/
EXTRACT_SUFX=	.tar

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Open source alternative to Magma, Maple, Mathematica and Matlab

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
