# Created by: Jason Bacon <jwb@FreeBSD.org>
# $FreeBSD$

PORTNAME=	abinit
PORTVERSION=	7.10.5
CATEGORIES=	wip science
MASTER_SITES=	http://ftp.abinit.org/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Find total energy, charge density and electronic structure of systems

LICENSE=	GPLv3

USES=		fortran gmake pkgconfig
GNU_CONFIGURE=	yes

# FIXME: Put pkgconfig files in libdata

.include <bsd.port.mk>
