# $FreeBSD$

PORTNAME=	getopt
DISTVERSION=	1.20.0
CATEGORIES=	wip devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Used with Rscript to write scripts that accept short and long flags

# 2 or 3
LICENSE=	GPLv2
#LICENSE_FILE=	

USES=		cran

.include <bsd.port.mk>
