
PORTNAME=	mkcolor3_caret_fim
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Assign colors via caret metric files

PLIST_FILES=	bin/mkcolor3_caret_fim

MAN1=		mkcolor3_caret_fim.1

.include <bsd.port.mk>
