
PORTNAME=	ginkgocadx
PORTVERSION=	3.8.7
CATEGORIES=	wip

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	DICOM viewer and dicomizer convert bitmaps to DICOM files

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LGPL3.txt

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	gerddie

.include <bsd.port.mk>
