PORTNAME=	TLv
PORTVERSION=	2003.03
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	MRI Reconstruction

PLIST_FILES=	bin/TLv

LIB_DEPENDS=	Xm.3:x11-toolkits/open-motif

MAN1=		TLv.1

.include <bsd.port.mk>
