# $FreeBSD$

PORTNAME=	spectra
PORTVERSION=	0.0.11
CATEGORIES=	wip graphics python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Color scales and color conversion made easy for Python.

LICENSE=	MIT
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
