# Created by: Jason Bacon <bacon@imacbsd.acadix.biz>
# $FreeBSD$

PORTNAME=	tensorflow
PORTVERSION=	1.0.0
DISTVERSIONPREFIX=v
CATEGORIES=	math

MAINTAINER=	bacon@imacbsd.acadix.biz
COMMENT=	Open-source software library for Machine Intelligence

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	bash:shells/bash

USES=		python
USE_GITHUB=	yes

HAS_CONFIGURE=	yes

.include <bsd.port.mk>
