PORTNAME=	vxl
PORTVERSION=	1.14.0
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	wip science
MASTER_SITES=	SF/vxl/vxl/1.14/

USE_ZIP=	yes
USE_CMAKE=	yes

MAINTAINER=	jwb@FreeBSD.org
COMMENT=
WWW=		https://port.home.page/

CFLAGS+=	-fPIC

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
