# New ports collection makefile for:	vxl
# Date created:		2012-05-06
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	vxl
PORTVERSION=	1.14.0
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	wip science
MASTER_SITES=	SF/vxl/vxl/1.14/

USE_ZIP=	yes
USE_CMAKE=	yes

MAINTAINER=	bacon4000@gmail.com
COMMENT=

CFLAGS+=	-fPIC

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
