PORTNAME=		pdf2htmlEX
DISTVERSIONPREFIX=	v
DISTVERSION=		0.18.7
DISTVERSIONSUFFIX=	-poppler-0.81.0
CATEGORIES=		wip converters

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Convert PDF to HTML
WWW=		https://github.com/pdf2htmlEX/pdf2htmlEX

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libfontforge.so:print/fontforge

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	pdf2htmlEX

.include <bsd.port.mk>
