# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	kwiklib
PORTVERSION=	0.3.0
DISTVERSIONPREFIX=      v
CATEGORIES=	math python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Shared features between the projects (files, statistics, utils)

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team

.include <bsd.port.mk>
