# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	gdc-client
PORTVERSION=	1.2.0
CATEGORIES=	ftp python
#MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Genomic Data Commons download tool

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	NCI-GDC

.include <bsd.port.mk>
