# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: head/biology/vcftools/Makefile 430483 2017-01-03 17:06:49Z jbeich $

PORTNAME=	vcftools
PORTVERSION=	0.1.11
# https://downloads.sourceforge.net/project/vcftools/vcftools_0.1.11.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fvcftools%2Ffiles%2F&ts=1509716670&use_mirror=phoenixnap
MASTER_SITES=	SF/vcftools
DISTNAME=	${PORTNAME}_${PORTVERSION}
CATEGORIES=	wip biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Tools for working with VCF genomics files

LICENSE=	LGPL3

USES=		gmake perl5 pkgconfig

.include <bsd.port.mk>
