PORTNAME=	cogent
PORTVERSION=	2016.10.04
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Reconstruct coding genome and group consensus isoforms from same locus
WWW=		https://github.com/Magdoll/Cogent

# No license specified
LICENSE=	PD
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	Magdoll
GH_TAGNAME=	e676f3f0cf77ec06250aa73499a0d63148d07b90

WRKSRC=		${WRKDIR}/Cogent-${GH_TAGNAME}

.include <bsd.port.mk>
