# New ports collection makefile for:	setfg
# Date created:		2007-05-04
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	setfg
PORTVERSION=	1.0
CATEGORIES=	misc
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

BUILD_DEPENDS=	${LOCALBASE}/lib/libtwin.a:../../devel/twintk \
		${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Set foreground and background colors on ASCII terminals

.include <bsd.port.mk>
