# New ports collection makefile for:	setfg
# Date created:		2007-05-04
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	setfg
PORTVERSION=	1.0
CATEGORIES=	misc
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/ \
		http://acadix.biz/Ports/distfiles/

BUILD_DEPENDS=	${LOCALBASE}/lib/libtwin.a:../../devel/twintk \
		${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

MAINTAINER=	jwbacon@tds.net
COMMENT=	Set foreground and background colors on ASCII terminals

.include <bsd.port.mk>
