# New ports collection makefile for:	dvdformat
# Date created:		8 Nov 2007
# Whom:			Jason W. Bacon
#
# $FreeBSD$
#

PORTNAME=	dvdformat
PORTVERSION=	0.1
CATEGORIES=	wip sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Format a DVDRAM and set ownership

PLIST_FILES=	bin/dvdformat

MAN1=		fixperms.1

.include <bsd.port.mk>
