# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	fastahack
PORTVERSION=	54d0711ca962d7a69788dc1f842a267a6c514e7f
CATEGORIES=	biology

MAINTAINER=	jwbacon@tds.net
COMMENT=	Utilities for indexing and sequence extraction from FASTA files

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

PLIST_FILES=	bin/fastahack lib/libfastahack.a

.include <bsd.port.mk>
