# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	fastahack
PORTVERSION=	18ed4b86ef962fa1b40f89b78625b2f271d9b155
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Utilities for indexing and sequence extraction from FASTA files

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
