# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	fastahack
PORTVERSION=	18ed4b86ef962fa1b40f89b78625b2f271d9b155
CATEGORIES=	biology

MAINTAINER=	jwbacon@tds.net
COMMENT=	Utilities for indexing and sequence extraction from FASTA files

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

PLIST_FILES=	bin/fastahack lib/libfastahack.a

.include <bsd.port.mk>
