PORTNAME=	openscenegraph
DISTVERSIONPREFIX=	OpenSceneGraph-
DISTVERSION=	3.6.5
CATEGORIES=	wip cad

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Open source high performance 3D graphics toolkit
WWW=		http://www.openscenegraph.com

# Fake: OpenSceneGraph license
LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		cmake

USE_GITHUB=	yes
GH_PROJECT=	OpenSceneGraph

.include <bsd.port.mk>
