PORTNAME=	streamvbyte
DISTVERSIONPREFIX=	v
DISTVERSION=	0.4.1
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Integer compression with SIMD on Google's Group Varint approach

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	lemire

.include <bsd.port.mk>
