# Created by: Jason Bacon <bacon@imacbsd.acadix.biz>
# $FreeBSD$

PORTNAME=	metagenomeSeq
DISTVERSION=	1.16.0
CATEGORIES=	biology
MASTER_SITES=	https://bioconductor.org/packages/release/bioc/src/contrib/
# DISTmetagenomeSeq_1.16.0.tar.gz
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	bacon@imacbsd.acadix.biz
COMMENT=	Determine features differentially abundant between groups of samples

LICENSE=	ART20
#LICENSE_FILE=	

USES=		cran:auto-plist

.include <bsd.port.mk>
