# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: head/textproc/xml-format/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xml-format
PORTVERSION=	0.2
CATEGORIES=	textproc
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	XML beautifier

LICENSE=	BSD2CLAUSE

USES+=		tar:xz

MAKE_ENV+=	DATADIR=${DATADIR} STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
