# $FreeBSD$

PORTNAME=	sailfish
DISTVERSIONPREFIX=	v
DISTVERSION=	0.10.0
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Rapid Mapping-based Isoform Quantification from RNA-Seq Reads

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	kingsfordgroup

.include <bsd.port.mk>
