# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	ea-utils
PORTVERSION=	1.1.2
CATEGORIES=	biology
MASTER_SITES=	http://acadix.biz/Ports/distfiles/
DISTNAME=	${PORTNAME}.${PORTVERSION}-806

MAINTAINER=	jwbacon@tds.net
COMMENT=	Command-line tools for processing fastq sequence data

.include <bsd.port.mk>
