#!/bin/sh -e

make clean build
cd work/ea-utils.1.1.2-806/t
mkdir tmp/multx.t.XwLIW
../fastq-multx -l in/multx/master-barcodes.txt in/multx/mxtest_2.fastq in/multx/mxtest_1.fastq in/multx/mxtest_3.fastq -o n/a -o tmp/multx.t.XwLIW/mxout_%_1.fq -o tmp/multx.t.XwLIW/mxout_%_2.fq

