PORTNAME=	libcprime
DISTVERSION=	5.0.0
CATEGORIES=	wip deskutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Library for bookmarking, saving recent activites, managing settings
WWW=		https://gitlab.com/cubocore/libcprime

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake qt:6
USE_QT=		base:run tools:build
USE_LDCONFIG=	yes
USE_GITLAB=	yes

GL_ACCOUNT=	CuboCore
GL_TAGNAME=	v5.0.0

.include <bsd.port.mk>
