# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	ruffus
PORTVERSION=	2.6.3
CATEGORIES=	wip science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Light-weight Python Computational Pipeline Management

LICENSE=	MIT
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
