# $FreeBSD$

PORTNAME=	mshr
PORTVERSION=	2017.2.0
CATEGORIES=	wip
MASTER_SITES=	https://bitbucket.org/fenics-project/mshr/downloads/

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	mesh generation component of FEniCS

LICENSE=	GPLv3
#LICENSE_FILE=

USES=		cmake:outsource

.include <bsd.port.mk>
