PORTNAME=	ceas
PORTVERSION=	1.0.2
CATEGORIES=	wip python
MASTER_SITES=	http://liulab.dfci.harvard.edu/CEAS/src/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	CEAS-Package-${PORTVERSION}

MAINTAINER=	dsiercks@uwm.edu
COMMENT=	Cis-regulatory Element Annotation System

LICENSE=	ClArtistic

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
