PORTNAME=	pynast
PORTVERSION=	1.2.2
CATEGORIES=	wip biology
MASTER_SITES=	https://github.com/biocore/pynast/archive/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}
DISTFILES=	${PORTVERSION}${EXTRACT_SUFX}
DIST_SUBDIR=	${PORTNAME}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Nearest Alignment Space Termination tool
WWW=		https://github.com/biocore/biom-format

# Unknown
LICENSE=	PD

USES=		python:3.6+
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	pynast

.include <bsd.port.mk>
