# Created by: Jason Bacon <jwb@FreeBSD.org>
# $FreeBSD$

PORTNAME=	pynast
PORTVERSION=	1.2.2
CATEGORIES=	wip biology
MASTER_SITES=	https://github.com/biocore/pynast/archive/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}
DISTFILES=	${PORTVERSION}${EXTRACT_SUFX}
DIST_SUBDIR=	${PORTNAME}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Nearest Alignment Space Termination tool

# Unknown
LICENSE=	PD

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	pynast

.include <bsd.port.mk>
