# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	constants
PORTVERSION=	0.6.0
CATEGORIES=	wip devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Simple way to deal with environment constants

# Not sure about clauses
LICENSE=	BSD2CLAUSE
#LICENSE_FILE=

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
