PORTNAME=	constants
PORTVERSION=	0.6.0
CATEGORIES=	wip devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Simple way to deal with environment constants

# Not sure about clauses
LICENSE=	BSD2CLAUSE
#LICENSE_FILE=

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
