# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	pedstats
PORTVERSION=	0.6.12
CATEGORIES=	wip biology
MASTER_SITES=	http://csg.sph.umich.edu/abecasis/PedStats/download/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Quick validation and summary of pedigree and data files

# LICENSE=	unspecified

USES=		gmake

PLIST_FILES=	bin/pedstats

INSTALL_TARGET=	INSTALLDIR=${STAGEDIR}${PREFIX}/bin install

.include <bsd.port.mk>
