# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	detonate
PORTVERSION=	1.8.1
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	DE novo TranscriptOme rNa-seq Assembly with or without the Truth Evaluation

# FIXME: Not sure
LICENSE=	PD
#LICENSE_FILE=	

USE_GITHUB=	yes
GH_ACCOUNT=	deweylab

.include <bsd.port.mk>
