# New ports collection makefile for:	detab
# Date created:		2011-01-04
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	detab
PORTVERSION=	0.1
CATEGORIES=	textproc
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Replace tabs a th spaces in a text file

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
