# New ports collection makefile for:	detab
# Date created:		2011-01-04
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	detab
PORTVERSION=	0.1
CATEGORIES=	textproc
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Replace tabs a th spaces in a text file

USES=		tar:xz

.include <bsd.port.mk>
