PORTNAME=	papp
DISTVERSION=	0.0.0-8
CATEGORIES=	wip devel
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Assembly Preprocessor

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	2db859cc

MAKE_ARGS+=	PREFIX=${PREFIX} \
		MANPREFIX=${PREFIX} \
		STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
