PORTNAME=	papp
DISTVERSION=	0.0.0-9
CATEGORIES=	wip devel
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Assembly Preprocessor

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	6e8aae18

.include <bsd.port.mk>
