PORTNAME=	papp
PORTVERSION=	0.3.2
CATEGORIES=	wip devel
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Assembly Preprocessor

LICENSE=	BSD3CLAUSE

USES=		tar:xz

MAKE_ARGS+=	PREFIX=${PREFIX} \
		MANPREFIX=${PREFIX} \
		STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
