PORTNAME=	BespON
DISTVERSION=	0.6.0
CATEGORIES=	wip textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Encode and decode data in the BespON format
WWW=		https://pypi.python.org/project/bespon/

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
