
PORTNAME=	tablet
DISTVERSION=	1.17.08.17
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Graphical viewer for next generation sequence assemblies and alignments

LICENSE=	BSD2CLAUSE
# LICENSE_FILE=	${WRKSRC}/LICENSE	Added after last release

USE_GITHUB=	yes

GH_ACCOUNT=	cropgeeks

.include <bsd.port.mk>
