# $FreeBSD$

PORTNAME=	SeqLib
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	C++ htslib/bwa-mem/fermi interface for interrogating sequence data

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	walaj
GH_TAGNAME=	62857243562cf1e4cd89f74f0cbd4c14b0a64e37

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
