# Created by: Jason Bacon <bacon@unixdev.ceas.uwm.edu>
# $FreeBSD$


PORTNAME=	libgtextutils
PORTVERSION=	0.7
CATEGORIES=	biology
MASTER_SITES=	https://github.com/agordon/libgtextutils/releases/download/0.7/

MAINTAINER=	bacon@unixdev.ceas.uwm.edu
COMMENT=	Gordon text utilities

# Just for speed: Recent GCC has better optimizer
USE_GCC=	yes
GNU_CONFIGURE=	yes
USES=		pkgconfig

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
