# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	libgtextutils
PORTVERSION=	0.7
CATEGORIES=	biology

MAINTAINER=	jwbacon@tds.net
COMMENT=	Gordon text utilities

LICENSE=	AGPLv3

GNU_CONFIGURE=	yes
USES=		libtool pkgconfig

USE_GITHUB=	yes
GH_ACCOUNT=	agordon
GH_PROJECT=	libgtextutils

.include <bsd.port.mk>
