# New ports collection makefile for:	boinc-einstein-brp
# Date created:		2013-10-08
# Whom:			Jason Bacon <bacon@sculpin.jbacon.dyndns.org>
#
# $FreeBSD$
#

PORTNAME=	boinc-einstein-brp
PORTVERSION=	
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=
MASTER_SITES=	http://einstein.phys.uwm.edu/download/brp-src-release.zip
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
#DISTNAME=
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bacon@sculpin.jbacon.dyndns.org
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
