# Created by:	Jason Bacon
# $FreeBSD$

# http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/10/Fedora/i386/os/Packages/binutils-2.18.50.0.9-7.fc10.i386.rpm
PORTNAME=	binutils-devel
PORTVERSION=	2.18.50.0.9
CATEGORIES=	devel linux
MASTER_SITES=	http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/10/Fedora/i386/os/Packages/
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	GNU Compiler Collection C compiler

USE_LINUX_RPM=	yes
LINUX_DIST_VER=	10
RPMVERSION=	7.fc10

.include <bsd.port.mk>
