# Created by: Jason Bacon <bacon@sculpin.acadix.biz>
# $FreeBSD$

PORTNAME=	oligotyping
PORTVERSION=	1.7
CATEGORIES=	biology
MASTER_SITES=	http://oligotyping.org/files/downloads/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Minimum entrop decomposition

# Deps:
# http://oligotyping.org/2014/08/16/installing-the-oligotyping-pipeline/
# py27-pip py27-scipy py27-matplotlib py27-biopython py27-django git
# R: 'vegan', 'ggplot2', 'gplots', 'gtools', 'reshape', 'optparse', 'pheatmap', 'RColorBrewer', 'compute.es'
# BLAST+

USES=		python:2 shebangfix
USE_PYTHON=	distutils
#SHEBANG_FILES=	scripts/ec2Clean scripts/ec2Dispatch

.include <bsd.port.mk>
