# New ports collection makefile for:	complex
# Date created:		2011-10-13
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	complex
PORTVERSION=	0.1
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	math science
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Complex math functions

NO_STAGE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
