#!/bin/sh

if [ $# != 1 ]; then
    printf "Usage: $0 filename\n"
    exit 1
fi

pkg_add $1 2> pkg_add_errors

if [ $? != 0 ]; then
    printf "Installation failed.\n"
    pkg_names=`awk ' { print $6 }' pkg_add_errors`

    for name in $pkg_names; do
	base_name=${name%-*}
	printf "$1 needs $base_name...\n"
	pkg_add -r $base_name
    done

    printf "Trying $1 again...\n"
    pkg_add $1
    rm pkg_add_errors
fi

