PORTNAME=		IsoSeq3
DISTVERSION=		3.0.0
DISTVERSIONPREFIX=	v
CATEGORIES=		wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Scalable De Novo Isoform Discovery from Single-Molecule PacBio Reads
WWW=		https://github.com/PacificBiosciences/IsoSeq3

LICENSE=	GPLv3
# LICENSE_FILE=	

USE_GITHUB=	yes
GH_ACCOUNT=	PacificBiosciences

.include <bsd.port.mk>
