PORTNAME=	parcel
PORTVERSION=	0.2.2
CATEGORIES=	wip www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Classes and helper functions for Python web applications

# Guessing
LICENSE=	GPLv2
#LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
