PORTNAME=	parmgridgen
PORTVERSION=	1.0
CATEGORIES=	wip science math
# http://freefoam.sf.net/nonfree/ParMGridGen-1.0.tar.gz
MASTER_SITES=	http://freefoam.sf.net/nonfree/
DISTNAME=	ParMGridGen-${PORTVERSION}
#MASTER_SITE_SUBDIR=

MAINTAINER=	jwb@FreeBSD.org
COMMENT=
WWW=		https://port.home.page/

FETCH_ARGS+=	-F

ALL_TARGET=	serial

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
