# $FreeBSD$

PORTNAME=	snakemake
PORTVERSION=	5.2.0
CATEGORIES=	wip python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Reduce the complexity of creating workflows

LICENSE=	MIT

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
