PORTNAME=	snakemake
PORTVERSION=	5.2.0
CATEGORIES=	wip python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Reduce the complexity of creating workflows
WWW=		https://pypi.python.org/pypi/snakemake

LICENSE=	MIT

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
