.TH FSL 1
.SH NAME    \" Section header
.PP

FSL - FMRIB Software Library

.SH SYNOPSIS
.PP
.nf 
.na 
fsl
.ad
.fi

\" Optional sections
.SH "DESCRIPTION"

.B FSL
is a comprehensive library of image analysis and statistical tools for
FMRI, MRI and DTI brain imaging data. FSL is written mainly by members of
the Analysis Group, FMRIB, Oxford, UK.

.B FSL
is far too complex to document in a man page.  For documentation, please
visit http://www.fmrib.ox.ac.uk/fsl/.

.SH ENVIRONMENT

.B FSL
requires many environment variables to be properly configured.
This is generally done by setting FSLDIR, and then running

.nf
.na
    source $FSLDIR/etc/fslconf/fsl.csh

or

    . $FSLDIR/etc/fslconf/fsl.sh
.ad
.fi

.SH "SEE ALSO"
afni(1), caret(1), freesurfer(1), dtiquery(1), nifticlib(3)

.SH AUTHOR
.nf
.na
FMRIB Analysis Group
http://www.fmrib.ox.ac.uk/analysis

