PORTNAME=	cosmos
PORTVERSION=	2.0.10
CATEGORIES=	wip biology
PKGNAMESUFFIX=	-wfm

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Python Workflow and Pipeline Management System

# http://cosmos.hms.harvard.edu/ says apache 2.0
# LICENSE file says GPL
LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	LPM-HMS
GH_PROJECT=	COSMOS2

.include <bsd.port.mk>
