PORTNAME=	q2templates
DISTVERSION=	2020.11.1
CATEGORIES=	wip python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Design template package for QIIME 2 Plugins
WWW=		https://github.com/qiime2/q2templates

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
USE_GITHUB=	yes

GH_ACCOUNT=	qiime2

.include <bsd.port.mk>
