# New ports collection makefile for:	ncbi_cxx
# Date created:		2011-07-30
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	ncbi_cxx
PORTVERSION=	9.0.0
CATEGORIES=	biology
MASTER_SITES=	ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/CURRENT/
# ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/CURRENT/ncbi_cxx--9_0_0.tar.gz
DISTNAME=	${PORTNAME}--9_0_0

MAINTAINER=	jwbacon@tds.net
COMMENT=	NCBI C++ toolkit

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
