# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	permute
DISTVERSION=	0.9-4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Restricted permutation designs for freely exchangeable, line transects

LICENSE=	GPLv2
#LICENSE_FILE=

USES=		cran

.include <bsd.port.mk>
