.TH \" Put title and section here, e.g. APE 1
.SH NAME    \" Section header
.PP

ddclone - Disk to disk clone
.SH SYNOPSIS
.PP
.nf 
.na 
ddclone
.ad
.fi

\" Optional sections
.SH WARNING - USE AT YOUR OWN RISK!
Use of
.B ddclone
WILL result in permanent loss of all data on the target disk.  Be
sure to back up any important files ON BOTH DISKS before running this
utility.  If you should accidentally transpose the device names, YOU WILL
WIPE OUT YOUR INTENDED SOURCE DISK.
.SH "PURPOSE"
The 
.B ddclone
script duplicates a hard disk and all of its partitions (if possible)
to another disk of equal or different size.
.SH "DESCRIPTION"
The
.B ddclone
script attempts to clone one hard disk, including all partitions, to
another disk of equal or different size.

To invoke, simply run
.B ddclone.
The script prompts the user for all necessary information and checks for
sanity as much as possible.

If partitions are the same size,
.B ddclone
will use
.B dd
to duplicate the partition.  This makes it possible to clone non-FreeBSD
partitions, provided that the destination is exactly the same size.
Hence,
.ddclone
can be used to clone a multi-booted disk, as long as only the FreeBSD
slice is of a different size than the original.

If the disks are exactly the same size, the user is given the option of
cloning the entire disk with a single
.B dd
command.  Note that this is not necessarily faster, especially if the
filesystems are mostly empty.

Live filesystems can be cloned, provided that care is taken not to alter
them during the cloning process.
.SH "SEE ALSO"
dd, dump, restore

.SH BUGS
.B BUGS
section missing from man page.

.SH AUTHOR
.nf
.na
Jason W. Bacon
Medical College of Wisconsin

