
PORTNAME=	time
PORTVERSION=	1.7
CATEGORIES=	wip sysutils
MASTER_SITES=	http://ftp.gnu.org/gnu/time/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	GNU time command

USES=		gmake
GNU_CONFIGURE=	yes

BROKEN=		Does not use destdir

.include <bsd.port.mk>
