#
# $FreeBSD$
#

PORTNAME=	setfg
PORTVERSION=	1.0
CATEGORIES=	wip misc
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

BUILD_DEPENDS=	${LOCALBASE}/lib/libtwin.a:../../devel/twintk \
		${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Set foreground and background colors on ASCII terminals

.include <bsd.port.mk>
