# Created by: Jason Bacon <bacon@manatee.acadix.biz>
# $FreeBSD$

PORTNAME=	logic
PORTVERSION=	1.1.30
CATEGORIES=	sysutils
MASTER_SITES=	http://downloads.saleae.com/betas/1.1.30/
DISTNAME=	Logic+${PORTVERSION}+\(32-bit\)

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=

USES=		zip

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
