PORTNAME=	shUnit2
PORTVERSION=	2.1.7
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	xUnit based unit test framework for Bourne based shell scripts
WWW=		https://github.com/kward/shunit2

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	kward



.include <bsd.port.mk>
