PORTNAME=	collectl
PORTVERSION=	4.0.2
CATEGORIES=	wip sysutils
MASTER_SITES=	SF/collectl/collectl/collectl-${PORTVERSION}
DISTNAME=	${PORTNAME}-${PORTVERSION}.src

# http://downloads.sourceforge.net/project/collectl/collectl/collectl-4.0.2/collectl-4.0.2.src.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcollectl%2F&ts=1453390424&use_mirror=tcpdiag

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	reports statistics on cpu, disk, infiniband, lustre, memory, etc
WWW=		https://sourceforge.net/projects/collectl/

LICENSE=	ART10

NO_BUILD=	yes

.include <bsd.port.mk>
