# Created by: Jason Bacon <bacon@oyster.jbacon.dyndns.org>
# $FreeBSD$

PORTNAME=	hapmix
PORTVERSION=	1.2
CATEGORIES=	biology
MASTER_SITES=	http://cdn1.sph.harvard.edu/wp-content/uploads/sites/181/2012/10/

DISTFILES=	hapmix1.2.tar_.gz.zip
MAINTAINER=	bacon@oyster.jbacon.dyndns.org
COMMENT=

.include <bsd.port.mk>
