# New ports collection makefile for:	TLv
# Date created:		4 jan 2007
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	TLv
PORTVERSION=	2003.03
CATEGORIES=	science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	MRI Reconstruction

PLIST_FILES=	bin/TLv

LIB_DEPENDS=	Xm.3:${PORTSDIR}/x11-toolkits/open-motif

MAN1=		TLv.1

.include <bsd.port.mk>
