#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2018-04-17  Charlie &   Begin
##########################################################################

usage()
{
    printf "Usage: $0 port category\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

PORTSDIR=${PORTSDIR:-/usr/ports}
EDITOR=${EDITOR:-vi}

port=$1
category=$2

port=`echo $port | sed -e 's|/$||'`

if grep -w wip $PORTSDIR/wip/$port/Makefile | grep -v '^CATEGORIES'; then
    printf "$port contains references to wip.  Please fix and try again.\n"
    exit 1
fi

if fgrep '$FreeBSD' $PORTSDIR/wip/$port/Makefile | grep -v '^CATEGORIES'; then
    printf "$port contains \$FreeBSD\$ tag.  Please fix and try again.\n"
    exit 1
fi

if [ -e $PORTSDIR/$category/$port ]; then
    printf "$PORTSDIR/$category/$port already exists.  Overwrite? y/[n] \n"
    read overwrite
    if [ 0$overwrite != 0y ]; then
	exit
    fi
fi

rsync -av --delete $PORTSDIR/wip/$port $PORTSDIR/$category

sed -i '' '/^CATEGORIES/s|wip ||' $PORTSDIR/$category/$port/Makefile
cd $PORTSDIR/$category/$port
for file in Makefile pkg-descr; do
    $EDITOR $file
done
port-check

# If user chose to overwrite, that means the port already existed and should
# be in category/Makefile already
if [ 0$overwrite != 0y ]; then
    printf "Add port? y/[n] "
    read add
    if [ 0$add = 0y ]; then
	cd ..
	git add $port
	printf "Add $port to $category/Makefile.\n"
	pause
	$EDITOR Makefile
    fi
fi
