#!/bin/sh -e


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

cat << EOM

It's a good idea to update all installed packages and ports before reinstalling
FEniCS or anything else from WIP (Work-In-Progress) ports, to ensure that
all dependencies are current.  This is especially true if you have not
updated the system recently.

EOM
printf "Update system first? [y]/n "
read update_sys
if [ 0$update_sys != 0n ]; then
    auto-update-system --defaults
    printf "Be sure to reboot after reinstalling FEniCS if the base system was updated.\n"
    pause
fi

set +e
# Delete lowest level dependency to force removal of of all FEniCS packages
pkg delete -y py\*-ufl py\*-fiat py\*-instant py\*-dijitso py\*-ffc ufc
pkg autoremove -y
set -e
pkg install -y cmake hdf5 py36-numpy py36-matplotlib swig30 cgal suitesparse
wip-reinstall-port -nu -nr py-fenics

if [ 0$update_sys != 0n ]; then
    printf "Reboot? [y]/n "
    read reboot
    if [ 0$reboot != 0n ]; then
	shutdown -r now
    fi
fi
