#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

depends="scythe sickle bwa py27-ceas bowtie2 tophat cufflinks py27-MACS2 meme"

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete'
    $pkg_delete $depends || true
    pause
fi

pkg install -y python R boost-jam cmake py27-numpy || true
wip-reinstall-port biology/chipseq-peakcalling

