#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete -y py34-idr
set -e
pkg install -y python3
wip-reinstall-port py34-idr
