#!/bin/sh -e

case $(auto-os-release) in
FreeBSD*|RHEL7)
    ;;
*)
    printf "Unsupported OS: $(auto-os-release)\n"
    exit 1
esac

cluster-wip-update
pkg remove -y cluster-admin
wip-reinstall-port -nu -r auto-admin
wip-reinstall-port -nu -r cluster-admin
cluster-run 'pkg remove -y cluster-admin' all
cluster-run 'wip-reinstall-port -nu -r auto-admin' all
cluster-run 'wip-reinstall-port -nu -r cluster-admin' all
