#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete bolt-llm
set -e
pkg install -y boost-libs nlopt
wip-reinstall-port bolt-lmm

