#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete lilyterm
set -e
pkg install -y gettext-tools pkgconf vte
wip-reinstall-port lilyterm
