#!/bin/sh -e

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete'
    $pkg_delete tabixpp smithwaterman fastahack filevercmp fsom multichoose \
	intervaltree vcflib rainbow bamtools freebayes stacks \
	seqtk bedtools2 pear-merger ddocent || true
fi

pkg install -y samtools cd-hit openjdk cmake gnuplot parallel texinfo \
    gawk mawk htslib help2man vcftools trimmomatic
wip-reinstall-port ddocent

