#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg remove -y unanimity pbbam pbseqan pbcopper
set -e
pkg install -y meson seqan htslib swig30 boost-libs py27-numpy
wip-reinstall-port -nu -nr unanimity
