#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

depends="doxygen cmake ninja pkgconf qt5-buildtools qt5-qmake qwt5"

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete'
    $pkg_delete $depends || true
    pause
fi

pkg install -y $depends
printf "Add qt5 support in the vtk6 options dialog.\n"
pause
wip-reinstall-port visit

