#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete tensorflow
set -e
pkg install -y zip bazel
wip-reinstall-port tensorflow
