#!/bin/sh -e

set +e
# Delete lowest level dependency to force removal of of all FEniCS packages
pkg delete -y py\*-ufl py\*-fiat py\*-instant py\*-dijitso py\*-ffc ufc
pkg autoremove -y
set -e
pkg install -y cmake hdf5 py36-numpy py36-matplotlib swig30 cgal suitesparse
wip-reinstall-port -nu -nr py-fenics
