#!/bin/sh -e

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete'
    $pkg_delete tabixpp smithwaterman fastahack filevercmp fsom multichoose \
	intervaltree vcflib rainbow bamtools freebayes stacks \
	seqtk trimadap bedtools2 pear-merger vcftools ddocent || true
fi

pkg install -y unzip bwa samtools cd-hit openjdk cmake gnuplot parallel \
    texinfo gawk mawk htslib help2man trimmomatic unzip bwa vcftools \
    trimmomatic
wip-reinstall-port ddocent
