#!/bin/sh -e

##########################################################################
#   Script description:
#       Restore a port that has been removed
#       
#   History:
#   Date        Name        Modification
#   2020-01-07  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 commit-hash port\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

commit=$1
port=$2
git checkout $commit^ -- $port
