PORTNAME=	msgpack-numpy
DISTVERSION=	0.4.6.post0
CATEGORIES=	wip math python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Numpy data serialization using msgpack
WWW=		https://pypi.python.org/pypi/msgpack-numpy

LICENSE=	BSD3CLAUSE
# LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
