# $FreeBSD$

PORTNAME=		fastp
DISTVERSIONPREFIX=	v
DISTVERSION=		0.20.0
CATEGORIES=		wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Ultra-fast all-in-one FASTQ preprocessor

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake
USE_GITHUB=	yes

GH_ACCOUNT=	OpenGene

ALL_TARGET=	fastp
PLIST_FILES=	bin/fastp
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
