PORTNAME=	spikedetekt2
PORTVERSION=	0.3.0
DISTVERSIONPREFIX=      v
CATEGORIES=	wip python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Detecting and extracting spikes from raw recordings

# Assuming based on other klusta packages
LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	klustakwik>=0:wip/klustakwik

USES=		python:3.6+
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team

.include <bsd.port.mk>
