# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	structure-frontend
PORTVERSION=
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=
MASTER_SITES=
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
#DISTNAME=
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bacon4000@gmail.com
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
