# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	pear
PORTVERSION=	0.9.6
CATEGORIES=	biology
MASTER_SITES=	http://sco.h-its.org/exelixis/web/software/pear/files/
PKGNAMESUFFIX=	-merger
DISTNAME=	${PORTNAME}-${PORTVERSION}-src

MAINTAINER=	jwbacon@tds.net
COMMENT=	Memory-efficient and highly accurate pair-end read merger

# LICENSE=	Creative commons

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/pear man/man1/pear.1.gz

.include <bsd.port.mk>
