PORTNAME=	openhospital
DISTVERSIONPREFIX=	v
DISTVERSION=	1.14.2
CATEGORIES=	wip net
# Github tags only contain docs
MASTER_SITES=	https://github.com/informatici/openhospital/releases/download/v1.14.2/
PKGNAMESUFFIX=	-server
DISTNAME=	OpenHospital-v${DISTVERSION}-linux_x86_64-portable

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Free and open-source Health Information Management System (HIMS)
WWW=		https://example.com/oh-server

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

# TODO: Add mariadb/mysql dep

.include <bsd.port.mk>
