# Created by: Jason Bacon <bacon@unixdev.ceas.uwm.edu>
# $FreeBSD$

PORTNAME=	sumatra
PORTVERSION=	0.7.4
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Sumatra-${PORTVERSION}

MAINTAINER=	bacon@unixdev.ceas.uwm.edu
COMMENT=	A tool for automated tracking of computation-based scientific projects

LICENSE=	BSD2CLAUSE
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
