PORTNAME=	hgapi
PORTVERSION=	1.7.2
CATEGORIES=	wip devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Python API to Mercurial using the command-line interface

LICENSE=	BSD2CLAUSE
#LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
