# New ports collection makefile for:	ascecho
# Date created:		2008-08-24
# Whom:			Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

PORTNAME=	ascecho
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	jwbacon@tds.net
COMMENT=	File viewer that shows invisible characters

PLIST_FILES=	bin/ascecho

.include <bsd.port.mk>
