# Created by: lme
# $FreeBSD: head/devel/linux-c6-libglade2/Makefile 372445 2014-11-11 13:06:39Z xmj $

PORTNAME=	gconf2
PORTVERSION=	2.28.0
CATEGORIES=	devel linux
DISTNAME=	GConf2-2.28.0-6.el6

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	RPM of gconf2 (Linux CentOS ${LINUX_DIST_VER})

USE_LINUX=	c6
USE_LINUX_RPM=	yes

RPMVERSION=	3.1.el6
USE_LDCONFIG=	yes

# DOCSDIR=	usr/share/doc/${PORTNAME}-${PORTVERSION}
# PORTDOCS=	AUTHORS COPYING NEWS README
# DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

.include <bsd.port.mk>
