# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	pyqi
PORTVERSION=	0.3.2
CATEGORIES=	wip biology
MASTER_SITES=	https://pypi.python.org/packages/source/p/pyqi/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	GPLv2	# From qiime install site.  Double check this.

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	pyqi

.include <bsd.port.mk>
