
PORTNAME=	pyqi
PORTVERSION=	0.3.2
CATEGORIES=	wip biology
MASTER_SITES=	https://pypi.python.org/packages/source/p/pyqi/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	GPLv2	# From qiime install site.  Double check this.

USES=		python:3.6+
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	pyqi

.include <bsd.port.mk>
