# Created by: Jason Wayne Bacon <bacon@sciprog.ceas.uwm.edu>
# $FreeBSD$

PORTNAME=	infernal
PORTVERSION=	1.1.1
CATEGORIES=	biology
MASTER_SITES=	http://selab.janelia.org/software/infernal/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Search DNA databases for RNA structure and sequence similarities

GNU_CONFIGURE=	yes
USE_GCC=	any

.include <bsd.port.mk>
