PORTNAME=	wasabi
DISTVERSION=	0.7.0
CATEGORIES=	wip python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A lightweight console printing and formatting toolkit
WWW=		https://pypi.python.org/pypi/wasabi

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
