PORTNAME=	MST-Bench
DISTVERSION=	0.2.1-5
DISTVERSIONSUFFIX=	-g56750b2
CATEGORIES=	wip benchmarks

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Maximum sustainable throughput benchmark

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/mst-bench man/man1/mst-bench.1.gz

.include <bsd.port.mk>
