# Created by: Jason Bacon <jwb@FreeBSD.org>

PORTNAME=	twintk
DISTVERSION=	0.9.4-10
DISTVERSIONSUFFIX=	-g117fa85
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Misc functions

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libxtend.so:wip/libxtend

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

.include <bsd.port.mk>
