# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	vcflib
PORTVERSION=	1.0.0
CATEGORIES=	biology

MAINTAINER=	jwbacon@tds.net
COMMENT=	C++ library and CLI tools for parsing and manipulating VCF files

USE_GITHUB=	yes
GH_ACCOUNT=	ekg
GH_TAGNAME=	v${PORTVERSION}-rc0

USES=		compiler:openmp

WRKSRC=		${WRKDIR}/vcflib-${PORTVERSION}-rc0

.include <bsd.port.mk>
