# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: head/biology/vcftools/Makefile 430483 2017-01-03 17:06:49Z jbeich $

PORTNAME=	vcftools
PORTVERSION=	0.1.15
DISTVERSIONPREFIX=	v
CATEGORIES=	wip biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Tools for working with VCF genomics files

LICENSE=	LGPL3

USES=		autoreconf gmake perl5 pkgconfig

GNU_CONFIGURE=	yes
USE_GITHUB=	yes

.include <bsd.port.mk>
