# $FreeBSD$

PORTNAME=	FAMSA
DISTVERSIONPREFIX=	v
DISTVERSION=	1.2.4
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Algorithm for large-scale multiple sequence alignments

# Check this
LICENSE=	PD

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	refresh-bio

MAKEFILE=	makefile

.include <bsd.port.mk>
