--- build/env.cmake.orig	2022-12-12 20:10:20 UTC
+++ build/env.cmake
@@ -75,6 +75,9 @@ set(CMAKE_CXX_EXTENSIONS OFF)
 if ( ${CMAKE_SYSTEM_NAME} STREQUAL  "Darwin" )
     set(OS "mac")
     set(SHLX "dylib")
+elseif ( ${CMAKE_SYSTEM_NAME} STREQUAL  "FreeBSD" )
+    set(OS "freebsd")
+    set(SHLX "so")
 elseif ( ${CMAKE_SYSTEM_NAME} STREQUAL  "Linux" )
     set(OS "linux")
     set(SHLX "so")
@@ -97,6 +100,8 @@ elseif ( ${_system_processor} STREQUAL "aarch64")
     set(ARCH "arm64")
 elseif ( ${_system_processor} STREQUAL "x86_64")
     set(ARCH "x86_64")
+elseif ( ${_system_processor} STREQUAL "amd64")
+    set(ARCH "x86_64")
 elseif ( ${_system_processor} STREQUAL "AMD64")
     set(ARCH "x86_64")
 else ()
@@ -212,6 +217,7 @@ add_compile_definitions (PKGNAME=${OS}${BITS})
 
 include_directories(interfaces)
 include_directories(interfaces/os)
+include_directories(interfaces/os/freebsd)
 include_directories(interfaces/ext)
 
 if ( "GNU" STREQUAL "${CMAKE_C_COMPILER_ID}")
