# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$
#
# Do not upgrade this port beyond 0.9.x before testing with biology/py-qiime

PORTNAME=	burrito
PORTVERSION=	0.9.1
CATEGORIES=	wip biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Framework for wrapping and controlling command-line applications

# Not sure about clauses
LICENSE=	BSD2CLAUSE
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
