# Do not upgrade this port beyond 0.9.x before testing with biology/py-qiime

PORTNAME=	burrito
PORTVERSION=	0.9.1
CATEGORIES=	wip biology python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Framework for wrapping and controlling command-line applications
WWW=		https://pypi.python.org/pypi/burrito

# Not sure about clauses
LICENSE=	BSD2CLAUSE
#LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
