
PORTNAME=	q2studio
DISTVERSION=	2019.7.0
CATEGORIES=	wip biology python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Graphical interface for Qiime2

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
USE_GITHUB=	yes

GH_ACCOUNT=	qiime2

.include <bsd.port.mk>
