# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	cpat
PORTVERSION=	1.2.2
CATEGORIES=	biology
MASTER_SITES=	SF/rna-cpat/v${PORTVERSION}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	CPAT-${PORTVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Overcomes alignment search limitations using logistic regression model

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/doc/COPYING

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
