# Do not uprade this port beyond 1.x before testing with biology/py-qiime

PORTNAME=	qcli
PORTVERSION=	0.1.1
CATEGORIES=	wip biology
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
# See also pyqi, an expanded version of qcli
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	GPLv2	# From qiime install site.  Double check this.

USES=		python:3.6+
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	qcli

.include <bsd.port.mk>
