# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$
#
# Do not upgrade this port beyond 0.1.x before testing with biology/py-qiime

PORTNAME=	burrito-fillings
PORTVERSION=	0.1.1
CATEGORIES=	wip biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Burrito application controllers for bioinformatics

# Not sure of clauses
LICENSE=	BSD2CLAUSE
# LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
