# Do not upgrade this port beyond 0.1.x before testing with biology/py-qiime

PORTNAME=	burrito-fillings
PORTVERSION=	0.1.1
CATEGORIES=	wip biology python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Burrito application controllers for bioinformatics
WWW=		https://pypi.python.org/pypi/burrito-fillings

# Not sure of clauses
LICENSE=	BSD2CLAUSE
# LICENSE_FILE=	

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
