PORTNAME=	dijitso
# Caution: Must use version compatible with other FEniCS project ports
DISTVERSION=	2017.2.0
CATEGORIES=	wip math python
MASTER_SITES=	https://bitbucket.org/fenics-project/dijitso/downloads/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Python module for distributed just-in-time shared library building
WWW=		https://fenicsproject.org/

LICENSE=	LGPL3+
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
