
PORTNAME=	mpi4py-mpich2

LIB_DEPENDS=	libmpich.so:net/mpich2

CONFLICTS_INSTALL=	py*-mpi4py-openmpi-*

MASTERDIR=	${.CURDIR}/../py-mpi4py-openmpi

DESCR=		${MASTERDIR}/pkg-descr
DISTINFO_FILE=	${MASTERDIR}/distinfo

.include "${MASTERDIR}/Makefile"
