# $FreeBSD$

PORTNAME=	libbacon
DISTVERSION=	1.2.2-2
DISTVERSIONSUFFIX=	-g4baa1e5
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Misc functions

LICENSE=	BSD2CLAUSE

PLIST_FILES=	lib/libbacon.a include/bacon.h

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

.include <bsd.port.mk>
