PORTNAME=	singularity
PORTVERSION=	2.5.1
CATEGORIES=	wip

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	Container

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.md

GNU_CONFIGURE=	yes
USES=		autoreconf libtool
USE_GITHUB=	yes
GH_ACCOUNT=	singularityware

.include <bsd.port.mk>
