PORTNAME=	singularity
PORTVERSION=	2.5.1
CATEGORIES=	wip

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Container
WWW=		https://github.com/singularityware/singularity

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.md

GNU_CONFIGURE=	yes
USES=		autoreconf libtool
USE_GITHUB=	yes
GH_ACCOUNT=	singularityware

.include <bsd.port.mk>
