# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	klustaviewa
PORTVERSION=	0.3.0
CATEGORIES=	python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	GUI for spike sorting manual stage in Python

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	klusta-team
GH_TAGNAME=	v${PORTVERSION}

.include <bsd.port.mk>
