PORTNAME=	drmaa
PORTVERSION=	0.7.6
CATEGORIES=	wip sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	i@levsha.me
COMMENT=	Interact with DRMAA-compliant distributed resource management systems

LICENSE=	BSD3CLAUSE

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
