PORTNAME=	veins
DISTVERSION=	5.2
DISTVERSIONPREFIX=	${PORTNAME}-
CATEGORIES=	wip cad

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Open source vehicular network simulation framework
WWW=		http://veins.car2x.org/

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

BUILD_DEPENDS=	omnetpp>=0:wip/omnetpp

USES=		gmake python
# HAS_CONFIGURE=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	sommer

.include <bsd.port.mk>
