# $FreeBSD$

PORTNAME=	u3-tool
PORTVERSION=	0.3
CATEGORIES=	wip
# https://downloads.sourceforge.net/project/u3-tool/u3-tool/0.3/u3-tool-0.3.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fu3-tool%2Ffiles%2Flatest%2Fdownload&ts=1560031441
MASTER_SITES=	SF

MAINTAINER=	bacon@mako.acadix.biz
COMMENT=	Manage u3 partition on USB drive

LICENSE=	GPLv2
#LICENSE_FILE=	

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
