# Created by: lme
# $FreeBSD: head/devel/linux-c6-libglade2/Makefile 372445 2014-11-11 13:06:39Z xmj $

PORTNAME=	ORBit2
PORTVERSION=	2.14.17
CATEGORIES=	devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	RPM of ORBit2 (Linux CentOS ${LINUX_DIST_VER})

USE_LINUX=	c6
USE_LINUX_RPM=	yes

RPMVERSION=	5.el6
USE_LDCONFIG=	yes

DOCSDIR=	usr/share/doc/${PORTNAME}-${PORTVERSION}
PORTDOCS=	AUTHORS COPYING README TODO
# DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

.include <bsd.port.mk>
