# New ports collection makefile for:	hilbplug2ffmap
# Date created:		4 jan 2007
# Whom:			Jason W. Bacon
#
# $FreeBSD$
#

PORTNAME=	hilbplug2ffmap
PORTVERSION=	1.0
CATEGORIES=	science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Combine Hilbert delay plugout data into FFMap file

PLIST_FILES=	bin/hilbplug2ffmap

MAN1=		hilbplug2ffmap.1

.include <bsd.port.mk>
