PORTNAME=		multichoose
DISTVERSIONPREFIX=	v
DISTVERSION=		1.0.3.3	# Derived from abandoned ekg/multichoose
CATEGORIES=		wip math

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generate multiset combinations (n multichoose k)
WWW=		https://github.com/vcflib/multichoose

LICENSE=	MIT

USES=		python shebangfix
SHEBANG_FILES=	*.py
USE_GITHUB=	yes
GH_ACCOUNT=	vcflib
GH_TAGNAME=	255192e

MAKEFILE=	${FILESDIR}/Makefile
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
