
PORTNAME=	libffmap
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	FFMap common functions

BUILD_DEPENDS=	${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

PLIST_FILES=	lib/libFFMap.a \
		include/FFMap.h

.include <bsd.port.mk>
