# Created by: Dan Siercks <dsiercks@uwm.edu>
# $FreeBSD$

PORTNAME=	cdbfasta
PORTVERSION=	2010.07.22
CATEGORIES=	biology
MASTER_SITES=	http://acadix.biz/Ports/distfiles/ \
		http://personalpages.tds.net/~jwbacon/Ports/distfiles/

MAINTAINER=	dsiercks@uwm.edu
COMMENT=	Fast indexing and retrieval of fasta records from flat file databases.

LICENSE=        BSD4CLAUSE
WRKSRC=         ${WRKDIR}/${PORTNAME}

USES=		gmake

.include <bsd.port.mk>
