# Created by: Jason Bacon <bacon@manatee.acadix.biz>
# $FreeBSD$

PORTNAME=	lilyterm
PORTVERSION=	0.9.9.4
DISTVERSIONPREFIX=v
CATEGORIES=	wip

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	Lightweight, but functional terminal emulator

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gmake pkgconfig
USE_GNOME=	gtk20 vte
GNU_CONFIGURE=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	Tetralet
GH_PROJECT=	LilyTerm

.include <bsd.port.mk>
