# New ports collection makefile for:	alberta
# Date created:		2012-03-20
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	alberta
PORTVERSION=	2.0.1
CATEGORIES=	math
MASTER_SITES=	http://www.alberta-fem.de/Downloads/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Adaptive multiLevel finite element toolbox

LIB_DEPENDS=	blas:${PORTSDIR}/math/blas

USE_FORTRAN=	yes
GNU_CONFIGURE=	yes
USE_GL=		yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
