# New ports collection makefile for:	qiime
# Date created:		2013-08-22
# Whom:			Jason Bacon <bacon@sculpin.jbacon.dyndns.org>
#
# $FreeBSD$
#

PORTNAME=	qiime
PORTVERSION=	1.7.0
CATEGORIES=	biology science
MASTER_SITES=	https://github.com/qiime/qiime/archive/
DISTNAME=	${PORTVERSION}

MAINTAINER=	jwbacon@tds.net
COMMENT=

FETCH_ARGS=	-F

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
