PORTNAME=	hdmedians
DISTVERSION=	0.13
CATEGORIES=	wip math python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	High dimensional medians (medoid, geometric median, etc.)
WWW=		https://pypi.python.org/pypi/hdmedians

LICENSE=	APACHE20

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
