# Created by: Artyom Mirgorodskiy <artyom.mirgorodsky@gmail.com>

PORTNAME=	ksh
PORTVERSION=	20120801
CATEGORIES=	wip shells

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Korn shell

DESCR=		${.CURDIR}/../../shells/${PORTNAME}93/pkg-descr
RPMVERSION=	37.el6_9
USES=		linux:c6
USE_LDCONFIG=	yes
# USE_LINUX=	libssh2 nspr nss openldap
USE_LINUX_RPM=	nolib

.include <bsd.port.mk>
