# $FreeBSD$

PORTNAME=	fermi-lite
PORTVERSION=	0.1p20160823
CATEGORIES=	wip

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	C library for assembling Illumina short reads in small regions

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	lh3
GH_TAGNAME=	562638112b7992f4d7a243ccd9ab2b3bd08c6b08

INSTALL_TARGET=	install-strip

PLIST_FILES=	bin/fml-asm lib/libfml.a

.include <bsd.port.mk>
