# New ports collection makefile for:	remmina-plugin-xdmcp
# Date created:				24 June 2010
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD: ports/net/remmina-plugin-xdmcp/Makefile,v 1.1 2010/08/10 03:21:10 avl Exp $
#

PKGNAMESUFFIX=	-xdmcp

COMMENT=	Remmina plugin for XDMCP protocol

RUN_DEPENDS=	Xephyr:${PORTSDIR}/x11-servers/xephyr

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
