# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	lattice
DISTVERSION=	0.20-34
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Data visualization system with an emphasis on multivariate data

# grid, grDevices, graphics, stats, utils
# or 3
LICENSE=	GPLv2
#LICENSE_FILE=

USES=		cran gettext

.include <bsd.port.mk>
