# Created by: J. Bacon <jwb@FreeBSD.org>

PORTNAME=	biolibc
DISTVERSION=	0.1.1-22
DISTVERSIONSUFFIX=	-gedfe6b6
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Low-level high-performance bioinformatics library

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	auerlab

.include <bsd.port.mk>
