# $FreeBSD$

PORTNAME=		biolibc
DISTVERSION=		0.1.0-15
DISTVERSIONSUFFIX=	-g30e57ea
CATEGORIES=		wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	VCF input/output library

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	auerlab

.include <bsd.port.mk>
