# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	cutadapt
PORTVERSION=	1.8.3
CATEGORIES=	biology
MASTER_SITES=	CHEESESHOP
MASTER_SITE_SUBDIR=source/c/cutadapt
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Finds and removes adapter sequences, primers, poly-A tails, etc

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
