#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
if [ -e /usr/wip ]; then
    set +e
    pkg delete -y unanimity pbbam pbseqan pbcopper
    set -e
    pkg install -y cmake htslib
    wip-update
    cd /usr/wip/biology/unanimity
    make distclean clean-depends
    make -DBATCH install
else
    printf "No /usr/wip found.\n"
fi


