#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-08-26  Jasson BaconBegin
##########################################################################

usage()
{
    printf "Usage: $0 [pkgsrc-prefix]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -gt 1 ]; then
    usage
fi

if [ $# = 1 ]; then
    # Pkgsrc
    prefix=$1
    if [ -e $prefix ]; then
	cd $prefix/jb-wip
	svn up
	cd py-pbfalcon
	set +e
	pkg_delete -rv py27-isodate
	pkg_delete -rv dazz_db
	pkg_delete -rv daligner
	pkg_delete -rv py27-pypeflow
	pkg_delete -rv py27-networkx
	set -e
	bmake clean
	bmake clean-depends
	bmake
	# Do this late to minimize uninstalled time
	bmake deinstall
	bmake install
    fi
else
    # FreeBSD ports
    if [ -e /usr/wip ]; then
	set +e
	pkg delete -y py27-isodate dazz_db daligner py27-pypeflow \
	    py27-networkx py27-pbfalcon
	set -e
	pkg install -y py27-networkx
	wip-update
	cd /usr/wip/biology/py-pbfalcon
	make distclean clean-depends
	make -DBATCH install
    else
	printf "No /usr/wip found.\n"
    fi
fi

