#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

depends="scythe sickle bowtie2 tophat cufflinks"

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete -y'
    $pkg_delete $depends || true
    pause
fi

pkg install -y python R
wip-reinstall-port biology/rna-pipeline1

