#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

depends="bowtie bowtie2 samtools samtools01 jellyfish parafly p5-transdecoder \
    slclust Trimmomatic rsem"

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg delete -y'
    $pkg_delete $depends || true
    pause
fi

pkg install -y coreutils ruby bash openjdk gmake gcc perl5 samtools m4 \
    gettext-tools python R
wip-reinstall-port biology/trinity

