#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete -y openfoam flex scotch-openmpi
set -e
pkg install -y bison gmake openmpi
for pkg in textproc/flex cad/scotch-openmpi science/openfoam; do
    cd /usr/wip/$pkg
    make clean clean-depends
    make -DBATCH install
    make package
    cd ../..
done
