#!/bin/sh -e

##########################################################################
#   Main
##########################################################################

# FreeBSD ports
set +e
pkg delete -y unanimity pbbam pbseqan pbcopper
set -e
pkg install -y cmake htslib
wip-update
cd /usr/wip/biology/unanimity
make distclean clean-depends
make -DBATCH install


