# New ports collection makefile for:	gsflow
# Date created:		2010-05-14
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	gsflow
PORTVERSION=	1.1.1
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=
MASTER_SITES=	http://water.usgs.gov/nrp/gwsoftware/gsflow/
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
DISTNAME=	GSFLOWv1.1.1
WRKSRC=		${WRKDIR}/${DISTNAME}/src
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	bacon4000@gmail.com
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
