# $FreeBSD$

PORTNAME=		srsly
DISTVERSIONPREFIX=	v
DISTVERSION=		2.1.0
CATEGORIES=		wip python
MASTER_SITES=		CHEESESHOP
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Modern high-performance serialization utilities for Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

USE_GITHUB=	yes
GH_ACCOUNT=	explosion

.include <bsd.port.mk>
