PORTNAME=	mricron
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.sph.sc.edu/comd/rorden/mricron/
DISTNAME=	mricron
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

USE_ZIP=	yes

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Convert medical image files to nifti
WWW=		https://port.home.page/

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
