# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	qtools
PORTVERSION=	899e34a4876ba232f920105a437efe365efe5c5e
CATEGORIES=	wip graphics python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Some Python tools for Qt

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils

USE_GITHUB=	yes
GH_ACCOUNT=	rossant

.include <bsd.port.mk>
