# Created by: Ken Moore <ken@pcbsd.org>

PORTNAME=	lumina
PORTVERSION=	1.6.2
PORTEPOCH=	3
CATEGORIES=	wip x11

MAINTAINER=	lbartoletti@FreeBSD.org
COMMENT=	Lumina Desktop Environment (meta-port)

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	lumina-core>=0:wip/lumina-core \
		lumina-coreutils>=0:wip/lumina-coreutils \
		lumina-archiver>=0:wip/lumina-archiver \
		lumina-calculator>=0:wip/lumina-calculator \
		lumina-fileinfo>=0:wip/lumina-fileinfo \
		lumina-fm>=0:wip/lumina-fm \
		lumina-mediaplayer>=0:wip/lumina-mediaplayer \
		lumina-pdf>=0:wip/lumina-pdf \
		lumina-photo>=0:wip/lumina-photo \
		lumina-screenshot>=0:wip/lumina-screenshot \
		lumina-textedit>=0:wip/lumina-textedit

USES=		metaport

CONFLICTS_INSTALL=	lumina-1.2.*

.include <bsd.port.mk>
