# $FreeBSD$

PORTNAME=	pufferfish
DISTVERSIONPREFIX=	salmon-v
DISTVERSION=	1.0.0
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	An efficient index for the colored, compacted, de Bruijn graph

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake:noninja
USE_GITHUB=	yes
GH_ACCOUNT=	COMBINE-lab

.include <bsd.port.mk>
