# Created by: Jason Bacon <bacon@manatee.acadix.biz>
# $FreeBSD$

PORTNAME=	spark
PORTVERSION=	1.0.2
CATEGORIES=	sysutils
MASTER_SITES=	http://d3kbcqa49mib13.cloudfront.net/
EXTRACT_SUFX=	.tgz

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=

BUILD_DEPENDS+=	scala:${PORTSDIR}/lang/scala

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
