# New ports collection makefile for:	ascecho
# Date created:		2008-08-24
# Whom:			Jason Bacon <jwb@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	ascecho
PORTVERSION=	1.0
CATEGORIES=	wip sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	File viewer that shows invisible characters

PLIST_FILES=	bin/ascecho

.include <bsd.port.mk>
