PORTNAME=	ctokens
DISTVERSION=	0.0.0-8
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	
WWW=		https://example.com/ctokens

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling
GH_TAGNAME=	06357c100689b26e1fbc058c4458dd7312bebe27

PLIST_FILES=	bin/ctokens share/man/man1/ctokens.1.gz

.include <bsd.port.mk>
