PORTNAME=	moa
PORTVERSION=	0.11.24
CATEGORIES=	wip biology python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Lightweight workflows in bioinformatics
WWW=		https://github.com/mfiers/Moa

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python:3.6+
USE_PYTHON=	distutils

.include <bsd.port.mk>
