PORTNAME=	lattice
DISTVERSION=	0.20-34
CATEGORIES=	wip graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Data visualization system with an emphasis on multivariate data

# grid, grDevices, graphics, stats, utils
# or 3
LICENSE=	GPLv2
#LICENSE_FILE=

USES=		cran:auto-plist gettext

IGNORE=		Installed as part of R base

.include <bsd.port.mk>
