PORTNAME=	remountnfs
PORTVERSION=	0.1
CATEGORIES=	wip sysutils
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Remount all NFS partitions
WWW=		https://port.home.page/

PLIST_FILES=	bin/remountnfs

MAN1=		remountnfs.1

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
