# New ports collection makefile for:    arm-none-eabi-binutils
# Date created:         28 May 2011
# Whom:                 Jason Bacon <jwbacon@tds.net>
#
# $FreeBSD$
#

MAINTAINER=	jwbacon@tds.net

TGTARCH=	arm
TGTABI=		none-eabi
WITH_RTEMS_PATCHES=	no

MASTERDIR=	${.CURDIR}/../cross-binutils
.include "${MASTERDIR}/Makefile"
