# New ports collection makefile for:    arm-none-eabi-binutils
# Date created:         28 May 2011
# Whom:                 Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

MAINTAINER=	bacon4000@gmail.com

TGTARCH=	arm
TGTABI=		none-eabi
WITH_RTEMS_PATCHES=	no

MASTERDIR=	${.CURDIR}/../cross-binutils
.include "${MASTERDIR}/Makefile"
