# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	pyqi
PORTVERSION=	0.3.2
CATEGORIES=	biology
MASTER_SITES=	https://pypi.python.org/packages/source/p/pyqi/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwbacon@tds.net
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	GPLv2	# From qiime install site.  Double check this.

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	pyqi

.include <bsd.port.mk>
