# $FreeBSD$

PORTNAME=	snpeff
DISTVERSION=	5.0
CATEGORIES=	wip biology
MASTER_SITES=	https://snpeff.blob.core.windows.net/versions/
DISTNAME=	snpEff_latest_core

MAINTAINER=	bacon@moray.acadix.biz
COMMENT=	Genetic variant annotation and effect prediction toolbox

LICENSE=	LGPL3
#LICENSE_FILE=	

USES=		python:3.6+ zip
USE_JAVA=	yes

.include <bsd.port.mk>
