# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	parameters
PORTVERSION=	0.2.1
CATEGORIES=	wip devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Management of large, hierarchical parameter sets for modelling and simulation

LICENSE=	GPLv2
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
