# New ports collection makefile for:	arm-none-eabi-gcc
# Date created:		30 May 2011
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

MAINTAINER=	bacon4000@gmail.com

TGTARCH=	arm
TGTABI=		none-eabi
WITH_RTEMS_PATCHES=	no

MASTERDIR=	${.CURDIR}/../cross-gcc

.include "${MASTERDIR}/Makefile"
