# $FreeBSD$

PORTNAME=	centrifuge
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0.3
CATEGORIES=	wip

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Novel microbial classification engine

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	infphilo

.include <bsd.port.mk>
