PORTNAME=	runas
DISTVERSION=	0.1.0-11
DISTVERSIONSUFFIX=	-g8894f84
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Wrapper around su for running a command as another user

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/runas man/man1/runas.1.gz

.include <bsd.port.mk>
