PORTNAME=	runas
DISTVERSION=	0.1.1-9
DISTVERSIONSUFFIX=	-ge737b63
CATEGORIES=	wip sysutils

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Wrapper around su for running a command as another user
WWW=		https://github.com/outpaddling/runas

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/asroot bin/runas man/man1/asroot.1.gz man/man1/runas.1.gz

.include <bsd.port.mk>
