# $FreeBSD$

PORTNAME=	runas
DISTVERSION=	0.1.0-3
DISTVERSIONSUFFIX=	-gc696290
CATEGORIES=	wip sysutils

MAINTAINER=	bacon@coral.acadix.biz
COMMENT=	Wrapper around su for running a command as another user

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

PLIST_FILES=	bin/runas

.include <bsd.port.mk>
