# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	vcftools
PORTVERSION=	0.1.14
CATEGORIES=	biology
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	jwbacon@tds.net
COMMENT=

USES=		autoreconf gmake

GNU_CONFIGURE=	yes

USE_GITHUB=	yes
GH_TAGNAME=	v${PORTVERSION}

.include <bsd.port.mk>
