# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	vcftools
PORTVERSION=	0.1.14
CATEGORIES=	biology
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	bacon4000@gmail.com
COMMENT=

USES=		autoreconf gmake

GNU_CONFIGURE=	yes

USE_GITHUB=	yes
GH_TAGNAME=	v${PORTVERSION}

.include <bsd.port.mk>
