
PORTNAME=	fastq-join
PORTVERSION=	1.3.1
DISTVERSIONPREFIX=v
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Squared distance for anchored alignment joiner of ea-utils

LICENSE=	MIT

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	brwnj

CXXFLAGS+=	-D_WITH_GETLINE

PLIST_FILES=	bin/fastq-join

.include <bsd.port.mk>
