PORTNAME=	LINKS
PKGNAMESUFFIX=	-genomics
DISTVERSIONPREFIX=	v
DISTVERSION=	1.8.6
CATEGORIES=	wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Long Interval Nucleotide K-mer Scaffolder
WWW=		https://github.com/bcgsc/LINKS

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	bcgsc

.include <bsd.port.mk>
