PORTNAME=	libccmio
PORTVERSION=	2.6.1
CATEGORIES=	wip science math
# http://freefoam.sf.net/nonfree/libccmio-2.6.1.tar.gz
MASTER_SITES=	http://freefoam.sf.net/nonfree/
#MASTER_SITE_SUBDIR=

MAINTAINER=	jwb@FreeBSD.org
COMMENT=

FETCH_ARGS+=	-F

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
