PORTNAME=	formulaic_contrasts
DISTVERSION=	1.0.0
CATEGORIES=	wip math python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Build arbitrary contrasts for models defined with formulaic
WWW=		https://github.com/scverse/formulaic-contrasts

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist pep517

.include <bsd.port.mk>
