# New ports collection makefile for:	trialsto1d
# Date created:		4 jan 2007
# Whom:			Jason W. Bacon
#
# $FreeBSD$
#

PORTNAME=	trialsto1d
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generate 1D files from trial data

PLIST_FILES=	bin/trialsto1D

MAN1=		trialsto1D.1

.include <bsd.port.mk>
