# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$
#
# Do not upgrade this port before testing the new version with biology/py-qiime

PORTNAME=	swarm
PORTVERSION=	1.2.19
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Robust and fast clustering method for amplicon-based studies

LICENSE=	AGPLv3
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	torognes

INSTALL_TARGET=	install-strip

PLIST_FILES=	bin/swarm

.include <bsd.port.mk>
