# Created by: Piotr Kubaj <pkubaj@anongoth.pl>

PORTNAME=	libcap-ng
PORTVERSION=	0.7.5
DISTVERSIONSUFFIX=	-4.el7
CATEGORIES=	wip security

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	OpenJDK

# ??
LICENSE=	LGPL21+

USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes
SRC_DISTFILES=	#empty

CONFLICTS=	linux-c6-${PORTNAME}-[0-9]*

OPTIONS_DEFINE=	DOCS
OPTIONS_SUB=	yes

.include <bsd.port.mk>
