# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	incrna
PORTVERSION=	2017.03.22
CATEGORIES=	wip biology
MASTER_SITES=	http://archive.gersteinlab.org/proj/incrna/
DISTNAME=	incrna_without_data

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Machine learning based on computed features of genomic regions

# Guess
LICENSE=	PD
#LICENSE_FILE=	

.include <bsd.port.mk>
