# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: head/science/fvcom-mpi/Makefile 412349 2016-04-01 14:25:16Z mat $

PKGNAMESUFFIX=	-lxqt

MAINTAINER=	bacon4000@gmail.com

MASTERDIR=	${.CURDIR}/../qterminal

USES+=		lxqt
USE_LXQT=	lxqt

.include "${MASTERDIR}/Makefile"
