
PORTNAME=	ffmap
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Functional Field Map

BUILD_DEPENDS=	${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

PLIST_FILES=	bin/ffmap

MAN1=		ffmap.1

.include <bsd.port.mk>
