# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	beast-mcmc
PORTVERSION=	1.8.3
CATEGORIES=	wip biology
DISTVERSIONPREFIX=	v

MAINTAINER=	bacon4000@gmail.com
COMMENT=	

LICENSE=	LGPL21
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	beast-dev

.include <bsd.port.mk>
