# $FreeBSD$

PORTNAME=	qctool
DISTVERSION=	2.1.3
CATEGORIES=	wip
MASTER_SITES=	https://enkre.net/cgi-bin/code/qctool/tarball/3d76073841/
DISTNAME=	qctool-3d76073841

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Manipulation and quality control of gwas datasets

LICENSE=	BSL
LICENSE_FILE=	${WRKSRC}/LICENSE_1_0.txt

.include <bsd.port.mk>
