# $FreeBSD$

PORTNAME=		vcf2hap
DISTVERSION=		0.1.1-5
DISTVERSIONSUFFIX=	-g650ac3d
CATEGORIES=		wip biology

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generate .hap file from VCF for haplohseq

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	auerlab

PLIST_FILES=	bin/vcf2hap

.include <bsd.port.mk>
