PORTNAME=	docbook-tools
DISTVERSION=	0.0.0.9
CATEGORIES=	wip textproc

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Scripts and programs for processing DocBook XML
WWW=		https://github.com/outpaddling/docbook-tools

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	32e794b9741c4f668f1b3ac273526add682fb110

.include <bsd.port.mk>
