PORTNAME=	docbook-tools
DISTVERSION=	0.0.0.16
CATEGORIES=	wip textproc

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Scripts and programs for processing DocBook XML
WWW=		https://github.com/outpaddling/docbook-tools

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	e62cdc9617647ba4969ff93dccacab8fbc6f0cf1

.include <bsd.port.mk>
