PORTNAME=	docbook-tools
DISTVERSION=	0.0.0.3
CATEGORIES=	wip textproc

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Scripts and programs for processing DocBook XML

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	66f75eaf1c4914679e41dc7ff4b415fd4cb2661b

.include <bsd.port.mk>
