PORTNAME=	libgamepad
DISTVERSION=	0.1.2-4
DISTVERSIONSUFFIX=	-gcd7306c
CATEGORIES=	wip devel games

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generic gamepad API
WWW=		https://github.com/outpaddling/libgamepad/

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

.include <bsd.port.mk>
