# $FreeBSD: head/devel/libgamepad/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libgamepad
DISTVERSION=	0.1.2-1
DISTVERSIONSUFFIX=	-g615195b
CATEGORIES=	wip devel games

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generic gamepad API

LICENSE=	BSD2CLAUSE

USES=		tar:xz
USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling

MAKE_ARGS+=	MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
