# New ports collection makefile for:	complex
# Date created:		2011-10-13
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	complex
PORTVERSION=	0.1
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	wip math science
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Complex math functions

USES=		tar:xz

.include <bsd.port.mk>
