# Created by: Jason Bacon <bacon@manatee.acadix.biz>
# $FreeBSD$
#
# Do not upgrade this port beyond 0.1.x before testing with py-qiime

PORTNAME=	qiime-default-reference
PORTVERSION=	0.1.3
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon@manatee.acadix.biz
COMMENT=	Default reference data files for use with QIIME

LICENSE=	PD
#LICENSE=	CC BY-SA 3.0
#LICENSE_FILE=	

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
