#!/bin/sh

##########################################################################
#   Script description:
#       Install script for Condor scheduler
#
#   Arguments:
#       $1 = port name
#       $2 = mode (e.g. 'POST-INSTALL')
#
#   Returns:
#       Standard
#
#   History:
#   Date        Name        Modification
#   2011-11-22  J Bacon     Derived from Ganglia pkg-install
##########################################################################

u=condor
g=condor

# Place condor on a large partition so it can accommodate output files from
# jobs.  The default /var/db/condor could result in /var filling up with
# job output.
homedir=/home/condor

case $2 in
PRE-INSTALL)
    # Condor home dir was changed from /var/db/condor to /home/condor
    # after 7.6.6 to avoid filling up /var
    
    # Patch UIDs in case port framework was upgraded without upgrading
    # the entire ports tree
    sed -i '.bak' "s|/var/db/condor|$homedir|g" /usr/ports/UIDs
    
    # If condor user already exists, make sure home dir is updated
    pw usermod condor -d $homedir
    
    # If condor user exists and has old home directory, move it
    if [ -d /var/db/condor ] && [ ! -L /var/db/condor ]; then
	# Remove symbolic link from /home to /var/db if it exists
	if [ -L $homedir ]; then
	    /bin/rm -f $homedir
	elif [ -d $homedir ]; then
	    # Move condor home dir from /var/db to /home.  If both exist as
	    # directories, keep /var/db/condor.  This shouldn't happen, but
	    # might if old or new condor port was partially installed.
	    /bin/mv $homedir $homedir.old
	fi
	mv /var/db/condor /home
    fi
    ;;

POST-INSTALL)
    for dir in log spool config execute; do
	mkdir -p $homedir/$dir
    done
    chown -Rh $u:$g $homedir
    
    # Insurance in case someone messed with the link
    if [ -L /var/db/condor ]; then
	/bin/rm -f /var/db/condor
    fi
    
    # Condor is built to use the standard /var/db/condor
    /bin/ln -s $homedir /var/db
    ;;
esac

