# Created by: Jason Bacon <jwb@FreeBSD.org>
# $FreeBSD: head/devel/yaggo/Makefile 411420 2016-03-19 18:17:50Z mat $

PORTNAME=	yaggo
PORTVERSION=	1.5.10
DISTVERSIONPREFIX=	v
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Generate command line parser using getopt_long

LICENSE=	GPLv3

NO_ARCH=	yes
USE_RUBY=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	gmarcais

PLIST_FILES=	bin/yaggo man/man1/yaggo.1.gz share/doc/yaggo/README.md

.include <bsd.port.mk>
