PORTNAME=	ti99-c99
DISTVERSION=	0.0.0-13
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Clint Pulley's C99 for the TI-99 adapted for cross-compiling
WWW=		https://github.com/outpaddling/ti99-c99

# Check this
LICENSE=	PD
LICENSE_FILE=	${WRKSRC}/readme.txt

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	2463da5b4e35c870a877b2ba6f915d67c49459f5

PLIST_FILES=	bin/c99

.include <bsd.port.mk>
