PORTNAME=	ti99-c99
DISTVERSION=	0.0.0-19
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Clint Pulley's C99 for the TI-99 adapted for cross-compiling
WWW=		https://github.com/outpaddling/ti99-c99

# Check this
LICENSE=	PD
LICENSE_FILE=	${WRKSRC}/readme.txt

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	f34fc2248420305b4e1234a4dbc6d8235692bb28

PLIST_FILES=	bin/c99 bin/ti99cc

.include <bsd.port.mk>
