PORTNAME=	ti99-c99
DISTVERSION=	0.0.0-11
CATEGORIES=	wip devel

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Clint Pulley's C99 for the TI-99 adapted for cross-compiling
WWW=		https://github.com/outpaddling/ti99-c99

# Check this
LICENSE=	PD
LICENSE_FILE=	${WRKSRC}/readme.txt

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	cd3e53ea8e0fa0cba5e65f1e5808eb5a966098a9

PLIST_FILES=	bin/c99

.include <bsd.port.mk>
