# New ports collection makefile for:	biom-format
# Date created:		2013-08-22
# Whom:			Jason Bacon <bacon@sculpin.jbacon.dyndns.org>
#
# $FreeBSD$
#

PORTNAME=	biom-format
PORTVERSION=	1.1.2
CATEGORIES=	biology science
MASTER_SITES=	ftp://thebeast.colorado.edu/pub/biom-format-releases/

MAINTAINER=	bacon@sculpin.jbacon.dyndns.org
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
