#!/bin/sh -ex

printf "GOPATH = $GOPATH\n"

go get -u github.com/antzucaro/matchr
go get -u github.com/fiam/gounidecode/unidecode
go get -u github.com/surgebase/porter2
go get -u golang.org/x/text/runes
go get -u golang.org/x/text/transform
go get -u golang.org/x/text/unicode/norm

platform=`uname -s`
# GOOS=`uname -s`
# GOARCH=`uname -m`
# GOARCH=x86-64
# export GOOS GOARCH

go build -o xtract."$platform" xtract.go
go build -o rchive."$platform" rchive.go
