# $FreeBSD: head/textproc/xml-format/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	xml-format
DISTVERSION=	0.2.0
CATEGORIES=	wip textproc

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	XML beautifier

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	outpaddling

MAKE_ENV+=	DATADIR=${DATADIR} STAGEDIR=${STAGEDIR}

.include <bsd.port.mk>
