# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	smithwaterman
PORTVERSION=	c57ff47a006168c6f1289cc01cc5705f43567d86
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Smith-waterman-gotoh alignment algorithm

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

.include <bsd.port.mk>
