# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	smithwaterman
PORTVERSION=	8e667291798b785d698f0875e58da2710d740567
CATEGORIES=	biology

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Smith-waterman-gotoh alignment algorithm

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
