# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	multichoose
PORTVERSION=	d60d639af93f8720e019d824bb2405eb4523fb16
CATEGORIES=	math

MAINTAINER=	jwbacon@tds.net
COMMENT=	Generate multiset combinations (n multichoose k)

LICENSE=	MIT

USES=		shebangfix
SHEBANG_FILES=	*.py

USE_GITHUB=	yes
GH_ACCOUNT=	outpaddling
GH_TAGNAME=	${PORTVERSION}

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
