# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	qcli
PORTVERSION=	0.1.0
CATEGORIES=	biology
MASTER_SITES=	http://pypi.python.org/packages/source/q/qcli/
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bacon4000@gmail.com
# See also pyqi, an expanded version of qcli
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	GPLv2	# From qiime install site.  Double check this.

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	qcli

.include <bsd.port.mk>
