# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	qcli
PORTVERSION=	0.1.0
CATEGORIES=	biology
MASTER_SITES=	http://pypi.python.org/packages/source/q/qcli/

MAINTAINER=	jwbacon@tds.net
# See also pyqi, an expanded version of qcli
COMMENT=	wrapping general commands in multiple types of interfaces

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	qcli

.include <bsd.port.mk>
