# Created by: Jason Bacon <jwbacon@tds.net>
# $FreeBSD$

PORTNAME=	abinit
PORTVERSION=	7.10.5
CATEGORIES=	science
MASTER_SITES=	http://ftp.abinit.org/

MAINTAINER=	jwbacon@tds.net
COMMENT=	Find total energy, charge density and electronic structure of systems

LICENSE=	GPLv3

USES=		fortran gmake pkgconfig
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
