# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD$

PORTNAME=	metal
PORTVERSION=	2011.03.25
CATEGORIES=	biology
MASTER_SITES=	http://csg.sph.umich.edu/abecasis/Metal/download/
DISTNAME=	generic-metal-2011-03-25

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Meta-analysis of genomewide association scans

#LICENSE=	
#LICENSE_FILE=	

USES=		gmake

WRKSRC=		${WRKDIR}/generic-metal

PLIST_FILES=	bin/metal

.include <bsd.port.mk>
