# $FreeBSD$

PORTNAME=	fermi-lite
PORTVERSION=	0.1p20160901
CATEGORIES=	wip biology
PKGNAMESUFFIX=	-walaj

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	C library for assembling Illumina short reads in small regions

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	walaj
GH_TAGNAME=	5bc90f8d70e2b66184eccbd223a3be714c914365

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
