# New ports collection makefile for:	1dregression
# Date created:		4 jan 2007
# Whom:			Jason Bacon <bacon4000@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	1dregression
PORTVERSION=	1.0
CATEGORIES=	wip science
MASTER_SITES=	http://www.neuro.mcw.edu/~bacon/Ports/distfiles/ \
		http://bacon.is-a-geek.org/~bacon/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Calculate statistics on 1D files

BUILD_DEPENDS=	${LOCALBASE}/lib/libbacon.a:../../devel/libbacon

PLIST_FILES=	bin/1dregression

MAN1=		1dregression.1

.include <bsd.port.mk>
