PORTNAME=	openlb
PORTVERSION=	0.7r0
CATEGORIES=	wip science math
MASTER_SITES=	http://www.optilb.com/openlb/wp-content/uploads/2012/02/
DISTNAME=	olb-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Open Source lattice Boltzmann code

USE_GMAKE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
