PORTNAME=	uchime
PORTVERSION=	4.2.40
CATEGORIES=	wip biology
MASTER_SITES=	http://drive5.com/uchime/
DISTNAME=	uchime4.2.40_src

# Unbundle from mothur when finished?
MAINTAINER=	jwb@FreeBSD.org
COMMENT=	Algorithm for detecting chimeric sequences
WWW=		https://drive5.com/usearch/manual/uchime_algo.html

LICENSE=	PD

PLIST_FILES=	bin/uchime
MAKEFILE=	${FILESDIR}/Makefile

.include <bsd.port.mk>
